export const CAREER_CATEGORIES = [
  {
    id: 'healthcare',
    label: 'Healthcare & Medicine',
    emoji: '🏥',
    careers: [
      { name: 'Surgeon', salary: 350000, edu: 'Medical + Residency (12+ yrs)' },
      { name: 'Anesthesiologist', salary: 330000, edu: 'Medical + Residency (12 yrs)' },
      { name: 'Radiologist', salary: 315000, edu: 'Medical + Residency (12 yrs)' },
      { name: 'OB/GYN', salary: 240000, edu: 'Medical School + Residency (12 yrs)' },
      { name: 'Doctor / Physician', salary: 220000, edu: 'Medical School (8+ yrs)' },
      { name: 'CRNA (Nurse Anesthetist)', salary: 200000, edu: "Master's + Residency (7 yrs)" },
      { name: 'Pediatrician', salary: 200000, edu: 'Medical School + Residency (11 yrs)' },
      { name: 'Dentist', salary: 175000, edu: 'Dental School (8 yrs)' },
      { name: 'Pharmacist', salary: 128000, edu: 'PharmD (6 yrs)' },
      { name: 'Nurse Practitioner', salary: 115000, edu: "Master's Degree (6 yrs)" },
      { name: 'Midwife / Doula', salary: 115000, edu: 'Nursing + Certification (6 yrs)' },
      { name: 'Physical Therapist', salary: 95000, edu: 'Doctorate (7 yrs)' },
      { name: 'Psychologist / Therapist', salary: 90000, edu: 'Doctorate (8 yrs)' },
      { name: 'Occupational Therapist', salary: 88000, edu: "Master's (6 yrs)" },
      { name: 'Speech-Language Pathologist', salary: 85000, edu: "Master's Degree (6 yrs)" },
      { name: 'Nurse (RN)', salary: 82000, edu: 'BSN (4 yrs)' },
      { name: 'Dental Hygienist', salary: 80000, edu: "Associate's Degree (2 yrs)" },
      { name: 'Social Worker (LCSW)', salary: 65000, edu: "Master's Degree (6 yrs)" },
      { name: 'Registered Dietitian', salary: 65000, edu: "Bachelor's + RD Exam (4 yrs)" },
      { name: 'Medical Coder / Biller', salary: 48000, edu: 'Certificate (months)' },
    ],
  },
  {
    id: 'law',
    label: 'Law & Government',
    emoji: '⚖️',
    careers: [
      { name: 'Judge', salary: 180000, edu: 'Law + Experience (10+ yrs)' },
      { name: 'Tax Attorney', salary: 160000, edu: 'Law School + Tax LLM (8 yrs)' },
      { name: 'Lawyer / Attorney', salary: 135000, edu: 'Law School (7 yrs)' },
      { name: 'Compliance Officer', salary: 90000, edu: "Bachelor's + Experience (4 yrs)" },
      { name: 'Diplomat / Foreign Service Officer', salary: 90000, edu: "Bachelor's + Exam (4 yrs)" },
      { name: 'Politician / Elected Official', salary: 80000, edu: 'Law / Political Science' },
      { name: 'Paralegal', salary: 58000, edu: "Associate's + Cert (2 yrs)" },
      { name: 'Community Organizer', salary: 52000, edu: "Bachelor's Degree (4 yrs)" },
    ],
  },
  {
    id: 'stem',
    label: 'STEM & Technology',
    emoji: '💻',
    careers: [
      { name: 'AI / Machine Learning Engineer', salary: 160000, edu: 'CS Degree + Experience (4 yrs)' },
      { name: 'Cloud Architect', salary: 155000, edu: 'CS Degree + Certs (4 yrs)' },
      { name: 'Product Manager (Tech)', salary: 140000, edu: "Bachelor's + Experience" },
      { name: 'Software Engineer', salary: 130000, edu: 'CS Degree (4 yrs)' },
      { name: 'DevOps Engineer', salary: 130000, edu: 'CS Degree + Certs (4 yrs)' },
      { name: 'Pilot (Commercial)', salary: 130000, edu: 'Flight School (2-4 yrs)' },
      { name: 'Data Scientist', salary: 125000, edu: "Master's (4-6 yrs)" },
      { name: 'Mobile App Developer', salary: 120000, edu: 'CS Degree / Bootcamp (2-4 yrs)' },
      { name: 'Aerospace Engineer', salary: 120000, edu: 'Engineering Degree (4 yrs)' },
      { name: 'Statistician / Actuary', salary: 115000, edu: 'Math/Stats Degree (4 yrs)' },
      { name: 'Cybersecurity Analyst', salary: 110000, edu: 'CS Degree + Certs (4 yrs)' },
      { name: 'IT Project Manager', salary: 110000, edu: "Bachelor's + PMP Cert (4 yrs)" },
      { name: 'Database Administrator', salary: 100000, edu: 'CS Degree (4 yrs)' },
      { name: 'Biomedical Engineer', salary: 100000, edu: 'Engineering Degree (4 yrs)' },
      { name: 'UX/UI Designer', salary: 95000, edu: 'Design Degree / Portfolio' },
      { name: 'Civil Engineer', salary: 95000, edu: 'Engineering Degree (4 yrs)' },
      { name: 'Architect', salary: 90000, edu: "Master's (5-7 yrs)" },
      { name: 'Environmental Scientist', salary: 76000, edu: 'Science Degree (4 yrs)' },
    ],
  },
  {
    id: 'business',
    label: 'Business & Finance',
    emoji: '💰',
    careers: [
      { name: 'Venture Capitalist', salary: 200000, edu: 'MBA + Finance Experience' },
      { name: 'Investment Banker', salary: 180000, edu: 'Finance Degree (4 yrs)' },
      { name: 'Entrepreneur / CEO', salary: 150000, edu: 'Varies' },
      { name: 'Real Estate Investor', salary: 120000, edu: 'Self-taught / Varies' },
      { name: 'Financial Advisor / CFP', salary: 95000, edu: "Bachelor's + Cert (4 yrs)" },
      { name: 'Supply Chain Manager', salary: 95000, edu: "Bachelor's Degree (4 yrs)" },
      { name: 'Operations Manager', salary: 90000, edu: "Bachelor's Degree (4 yrs)" },
      { name: 'Marketing Manager', salary: 85000, edu: "Bachelor's Degree (4 yrs)" },
      { name: 'Business Analyst', salary: 85000, edu: "Bachelor's Degree (4 yrs)" },
      { name: 'Mortgage Loan Officer', salary: 85000, edu: "License + Bachelor's (4 yrs)" },
      { name: 'Brand Strategist', salary: 85000, edu: 'Marketing Degree (4 yrs)' },
      { name: 'Real Estate Agent', salary: 80000, edu: 'License (months)' },
      { name: 'Human Resources Manager', salary: 80000, edu: "Bachelor's Degree (4 yrs)" },
      { name: 'Accountant / CPA', salary: 78000, edu: "Bachelor's + CPA (4 yrs)" },
      { name: 'Insurance Underwriter', salary: 75000, edu: "Bachelor's Degree (4 yrs)" },
    ],
  },
  {
    id: 'creative',
    label: 'Creative & Media',
    emoji: '🎨',
    careers: [
      { name: 'Art Director', salary: 100000, edu: 'Design Degree (4 yrs)' },
      { name: 'Film Director', salary: 90000, edu: 'Film School / Portfolio' },
      { name: 'Music Producer', salary: 80000, edu: 'Music School / Self-taught' },
      { name: 'PR / Communications Manager', salary: 80000, edu: "Bachelor's Degree (4 yrs)" },
      { name: 'Animator / Motion Designer', salary: 78000, edu: 'Design Degree / Portfolio' },
      { name: 'Content Creator / Influencer', salary: 75000, edu: 'None required' },
      { name: 'Fashion Designer', salary: 70000, edu: 'Fashion Degree (4 yrs)' },
      { name: 'Podcast Host / Media Personality', salary: 70000, edu: 'None required' },
      { name: 'Interior Designer', salary: 65000, edu: 'Design Degree (4 yrs)' },
      { name: 'Graphic Designer', salary: 60000, edu: "Bachelor's / Portfolio" },
      { name: 'Event Planner', salary: 60000, edu: 'Hospitality Degree / Experience' },
      { name: 'Photographer / Videographer', salary: 58000, edu: 'Portfolio-based' },
      { name: 'Journalist / Writer', salary: 55000, edu: "Bachelor's Degree (4 yrs)" },
    ],
  },
  {
    id: 'beauty',
    label: 'Beauty, Wellness & Fitness',
    emoji: '💅',
    careers: [
      { name: 'Veterinarian', salary: 120000, edu: 'Vet School (8 yrs)' },
      { name: 'Cosmetology Business Owner', salary: 85000, edu: 'Cosmetology + Business' },
      { name: 'Personal Chef', salary: 70000, edu: 'Culinary School (2 yrs)' },
      { name: 'Chef / Restaurateur', salary: 65000, edu: 'Culinary School (2 yrs)' },
      { name: 'Tattoo Artist', salary: 60000, edu: 'Apprenticeship (2 yrs)' },
      { name: 'Fitness Trainer / Coach', salary: 55000, edu: 'Certification (months)' },
      { name: 'Makeup Artist (MUA)', salary: 55000, edu: 'Cosmetology / Portfolio' },
      { name: 'Barber / Barber Shop Owner', salary: 55000, edu: 'Barber License (months)' },
      { name: 'Nail Technician / Nail Artist', salary: 48000, edu: 'Nail Tech License (months)' },
      { name: 'Cosmetologist / Esthetician', salary: 45000, edu: 'Cosmetology School (1 yr)' },
    ],
  },
  {
    id: 'education',
    label: 'Education & Social Services',
    emoji: '📚',
    careers: [
      { name: 'School Principal', salary: 100000, edu: "Master's + Admin Cert (6 yrs)" },
      { name: 'Child Psychologist', salary: 95000, edu: 'Doctorate (8 yrs)' },
      { name: 'Professor / Academic', salary: 85000, edu: 'PhD (8+ yrs)' },
      { name: 'Nonprofit Director', salary: 75000, edu: "Master's Preferred (6 yrs)" },
      { name: 'Special Education Teacher', salary: 65000, edu: "Bachelor's + Cert (4 yrs)" },
      { name: 'Teacher / Educator', salary: 62000, edu: "Bachelor's + Cert (4 yrs)" },
      { name: 'School Counselor', salary: 62000, edu: "Master's Degree (6 yrs)" },
      { name: 'Childcare Center Director', salary: 55000, edu: "Bachelor's + Cert (4 yrs)" },
    ],
  },
  {
    id: 'trades',
    label: 'Public Safety & Skilled Trades',
    emoji: '🔧',
    careers: [
      { name: 'Military Officer', salary: 72000, edu: 'ROTC / Military Academy' },
      { name: 'Electrician (Licensed)', salary: 70000, edu: 'Apprenticeship (4 yrs)' },
      { name: 'Police Officer / Detective', salary: 68000, edu: 'Academy (months)' },
      { name: 'Truck Driver (CDL)', salary: 65000, edu: 'CDL License (months)' },
      { name: 'Firefighter', salary: 58000, edu: 'Academy (months)' },
      { name: 'HVAC Technician', salary: 58000, edu: 'Trade School (2 yrs)' },
      { name: 'Welder (Certified)', salary: 55000, edu: 'Trade School + Cert (1-2 yrs)' },
      { name: 'Paramedic / EMT', salary: 52000, edu: 'EMT Certification (months)' },
      { name: 'Correctional Officer', salary: 52000, edu: 'Academy (months)' },
    ],
  },
];

export const LIFESTYLE_CATEGORIES = [
  {
    id: 'home',
    label: 'Dream Home',
    emoji: '🏠',
    options: [
      { label: 'Apartment (1BR)', cost: 1200 },
      { label: 'Apartment (2BR)', cost: 1800 },
      { label: 'Townhouse', cost: 2500 },
      { label: 'Single Family Home', cost: 3200 },
      { label: 'Luxury Home', cost: 5000 },
    ],
  },
  {
    id: 'car',
    label: 'Dream Car',
    emoji: '🚗',
    options: [
      { label: 'No Car / Public Transit', cost: 100 },
      { label: 'Used Car', cost: 350 },
      { label: 'New Car (mid-range)', cost: 500 },
      { label: 'Luxury Car', cost: 900 },
      { label: 'Exotic Car', cost: 2000 },
    ],
  },
  {
    id: 'travel',
    label: 'Travel',
    emoji: '✈️',
    options: [
      { label: 'Domestic trips only', cost: 100 },
      { label: '1 international trip/year', cost: 250 },
      { label: '2-3 trips/year', cost: 500 },
      { label: 'Frequent traveler (4+/year)', cost: 1000 },
      { label: 'Luxury world traveler', cost: 2500 },
    ],
  },
  {
    id: 'fashion',
    label: 'Fashion & Shopping',
    emoji: '👗',
    options: [
      { label: 'Budget shopping', cost: 100 },
      { label: 'Mid-range brands', cost: 300 },
      { label: 'Designer pieces', cost: 600 },
      { label: 'Full designer wardrobe', cost: 1500 },
    ],
  },
  {
    id: 'wellness',
    label: 'Wellness & Self-Care',
    emoji: '🧘',
    options: [
      { label: 'Basic (gym + haircare)', cost: 150 },
      { label: 'Standard (spa + gym)', cost: 350 },
      { label: 'Premium (trainer + spa)', cost: 700 },
      { label: 'Luxury wellness lifestyle', cost: 1500 },
    ],
  },
  {
    id: 'giving',
    label: 'Giving & Charity',
    emoji: '💝',
    options: [
      { label: 'Small donations', cost: 50 },
      { label: 'Regular giving (5%)', cost: 200 },
      { label: 'Generous giver (10%)', cost: 500 },
      { label: 'Philanthropist (20%+)', cost: 1500 },
    ],
  },
];

export const KIDS_OPTIONS = [
  { label: 'No kids', value: 0, cost: 0 },
  { label: '1 child', value: 1, cost: 1200 },
  { label: '2 children', value: 2, cost: 2200 },
  { label: '3 children', value: 3, cost: 3000 },
  { label: '4+ children', value: 4, cost: 3700 },
];

export const CAREER_MATCH = {
  budget: {
    label: 'Budget',
    range: '< $2,500/mo',
    careers: [
      { name: 'Teacher / Educator', salary: '$62K/yr', path: "Bachelor's + Cert" },
      { name: 'Social Worker (LCSW)', salary: '$65K/yr', path: "Master's Degree" },
      { name: 'Nurse (RN)', salary: '$82K/yr', path: 'BSN (4 yrs)' },
      { name: 'Dental Hygienist', salary: '$80K/yr', path: "Associate's (2 yrs)" },
      { name: 'Real Estate Agent', salary: '$80K/yr', path: 'License (months)' },
    ],
  },
  moderate: {
    label: 'Moderate',
    range: '$2,500–$5,000/mo',
    careers: [
      { name: 'Pharmacist', salary: '$128K/yr', path: 'PharmD (6 yrs)' },
      { name: 'Software Engineer', salary: '$130K/yr', path: 'CS Degree (4 yrs)' },
      { name: 'Nurse Practitioner', salary: '$115K/yr', path: "Master's (6 yrs)" },
      { name: 'Entrepreneur / CEO', salary: '$150K+/yr', path: 'Varies' },
      { name: 'Real Estate Investor', salary: '$120K/yr', path: 'Self-taught' },
      { name: 'Lawyer / Attorney', salary: '$135K/yr', path: 'Law School (7 yrs)' },
    ],
  },
  luxury: {
    label: 'Luxury',
    range: '$5,000–$9,000/mo',
    careers: [
      { name: 'Pharmacist', salary: '$128K/yr', path: 'PharmD (6 yrs)' },
      { name: 'Software Engineer', salary: '$130K/yr', path: 'CS Degree (4 yrs)' },
      { name: 'Lawyer / Attorney', salary: '$135K/yr', path: 'Law School (7 yrs)' },
      { name: 'CRNA (Nurse Anesthetist)', salary: '$200K+/yr', path: "Master's (7 yrs)" },
      { name: 'Entrepreneur / CEO', salary: '$150K+/yr', path: 'Varies' },
      { name: 'AI / ML Engineer', salary: '$160K/yr', path: 'CS Degree (4 yrs)' },
    ],
  },
  elite: {
    label: 'Elite',
    range: '> $9,000/mo',
    careers: [
      { name: 'Surgeon', salary: '$350K/yr', path: 'Medical + Residency (12 yrs)' },
      { name: 'Anesthesiologist', salary: '$330K/yr', path: 'Medical + Residency (12 yrs)' },
      { name: 'Radiologist', salary: '$315K/yr', path: 'Medical + Residency (12 yrs)' },
      { name: 'Investment Banker', salary: '$180K/yr', path: 'Finance Degree (4 yrs)' },
      { name: 'Venture Capitalist', salary: '$200K+/yr', path: 'MBA + Finance' },
      { name: 'Entrepreneur / CEO', salary: '$150K+/yr', path: 'Varies' },
      { name: 'Tax Attorney', salary: '$160K/yr', path: 'Law School + LLM (8 yrs)' },
    ],
  },
};

export const GLOW_ROADMAP = [
  {
    age: 'Age 15–18',
    label: 'Plant Your Seeds',
    emoji: '🌱',
    color: '#22c55e',
    steps: [
      'Focus on grades — GPA opens doors to scholarships',
      'Research scholarships now (start a list!)',
      'Build confidence & communication skills',
      'Open a savings account & save any income',
      'Explore career options through shadowing & research',
      'Start building your personal brand online',
    ],
  },
  {
    age: 'Age 18–22',
    label: 'Build Your Foundation',
    emoji: '🌸',
    color: '#a855f7',
    steps: [
      'College, trade school, or certification program',
      'Apply for every scholarship & grant available',
      'Land internships & part-time work in your field',
      'Build an emergency fund (3 months of expenses)',
      'Start a Roth IRA — even $50/mo compounds big',
      'Network intentionally — your circle = your net worth',
    ],
  },
  {
    age: 'Age 22–26',
    label: 'Level Up Your Income',
    emoji: '✨',
    color: '#818cf8',
    steps: [
      'Negotiate your first salary — never accept the first offer',
      'Max out employer 401k match (free money!)',
      'Pay down high-interest debt aggressively',
      'Start investing in index funds',
      'Build a side hustle or freelance income stream',
      'Learn real estate basics — homeownership is wealth',
    ],
  },
  {
    age: 'Age 26–30',
    label: 'Build Your Empire',
    emoji: '👑',
    color: '#f59e0b',
    steps: [
      'Buy your first home or investment property',
      'Diversify income: stocks, real estate, business',
      'Grow your career into leadership or ownership',
      'Give back — mentor younger girls',
      'Protect your wealth: life insurance, will, trust',
      'Live your dream life on YOUR terms 👑',
    ],
  },
];