export const CAREER_CATEGORIES = [
  {
    id: 'beauty_wellness',
    label: 'Beauty & Wellness',
    emoji: '💄',
    careers: [
      { name: 'Makeup Artist', salary: 75000, edu: 'Cosmetology/esthetics school (6–12 months)' },
      { name: 'Esthetician', salary: 55000, edu: 'Esthetics program (4–12 months)' },
      { name: 'Hairstylist', salary: 65000, edu: 'Cosmetology school (9–12 months)' },
      { name: 'Nail Technician', salary: 50000, edu: 'Nail technician program (3–6 months)' },
      { name: 'Lash Technician', salary: 65000, edu: 'Lash extension certification course' },
      { name: 'Barber', salary: 65000, edu: 'Barber school (9–12 months)' },
      { name: 'Skincare Brand Owner', salary: 120000, edu: 'Cosmetic chemistry + business knowledge' },
      { name: 'Perfumer', salary: 100000, edu: 'Fragrance/cosmetic chemistry courses' },
      { name: 'Image Consultant', salary: 90000, edu: 'Image consulting certification' },
      { name: 'Personal Stylist', salary: 90000, edu: 'Fashion/merchandising degree (optional)' },
      { name: 'Cosmetic Chemist', salary: 95000, edu: 'Chemistry or cosmetic science degree' },
      { name: 'Spa Owner', salary: 130000, edu: 'Esthetics/cosmetology + business management' },
      { name: 'Beauty Influencer', salary: 80000, edu: 'Start creating content today' },
    ],
  },
  {
    id: 'business',
    label: 'Business',
    emoji: '💼',
    careers: [
      { name: 'Entrepreneur / Business Owner', salary: 150000, edu: 'No degree required (optional Business degree)' },
      { name: 'Marketing Manager', salary: 100000, edu: 'Marketing or Business degree' },
      { name: 'Human Resources Manager', salary: 95000, edu: "Bachelor's in HR, Business, or Psychology" },
      { name: 'Accountant / CPA', salary: 95000, edu: "Accounting or Finance degree + CPA exam" },
      { name: 'Mortgage Loan Officer', salary: 100000, edu: "Bachelor's in Finance or Business + NMLS license" },
      { name: 'Project Manager', salary: 105000, edu: "Bachelor's in Business + PMP certification" },
      { name: 'Event Planner', salary: 70000, edu: 'Event management degree (optional) + CMP cert' },
      { name: 'Sales Executive', salary: 130000, edu: "Bachelor's in Business or Communications" },
      { name: 'Business Consultant', salary: 160000, edu: "Bachelor's in Business/Economics + MBA" },
      { name: 'Executive Assistant', salary: 80000, edu: "Associate's or Bachelor's degree" },
      { name: 'Operations Manager', salary: 100000, edu: "Bachelor's in Business + Lean Six Sigma" },
      { name: 'Public Relations Specialist', salary: 85000, edu: "Bachelor's in PR, Communications, or Journalism" },
      { name: 'Recruiter', salary: 90000, edu: "Bachelor's in HR, Business, or Psychology" },
    ],
  },
  {
    id: 'creative_media',
    label: 'Creative & Media',
    emoji: '🎬',
    careers: [
      { name: 'Actress', salary: 80000, edu: 'Acting classes + BFA in Theatre (optional)' },
      { name: 'Singer', salary: 85000, edu: 'Vocal lessons + music theory' },
      { name: 'Dancer / Choreographer', salary: 70000, edu: 'Dance training + BFA in Dance (optional)' },
      { name: 'Author / Writer', salary: 80000, edu: 'English/Creative Writing degree (optional)' },
      { name: 'Screenwriter', salary: 180000, edu: 'Film or Creative Writing degree' },
      { name: 'Film Producer', salary: 250000, edu: 'Film production or business degree' },
      { name: 'Photographer', salary: 90000, edu: 'Photography courses + portfolio' },
      { name: 'Journalist', salary: 75000, edu: 'Journalism or Communications degree' },
      { name: 'Radio Host', salary: 120000, edu: 'Communications or Broadcasting degree' },
      { name: 'TV Host', salary: 200000, edu: 'Communications, Journalism, or Theatre degree' },
      { name: 'Influencer', salary: 120000, edu: 'Start posting today — find your niche' },
      { name: 'Model', salary: 80000, edu: 'Signed with a reputable agency + portfolio' },
      { name: 'Music Producer', salary: 180000, edu: 'Music production software + music theory' },
      { name: 'YouTuber', salary: 90000, edu: 'Start your channel today' },
      { name: 'Podcaster', salary: 80000, edu: 'Start recording now — learn audio editing' },
      { name: 'Animator', salary: 90000, edu: 'Animation or Fine Arts degree' },
    ],
  },
  {
    id: 'creative_arts',
    label: 'Creative Arts',
    emoji: '👗',
    careers: [
      { name: 'Fashion Designer / Stylist', salary: 90000, edu: 'Fashion design degree OR self-taught + portfolio' },
    ],
  },
  {
    id: 'design',
    label: 'Design',
    emoji: '🏛️',
    careers: [
      { name: 'Architect / Interior Designer', salary: 90000, edu: 'Architecture/Interior Design degree (5 years)' },
    ],
  },
  {
    id: 'education',
    label: 'Education',
    emoji: '📚',
    careers: [
      { name: 'Teacher / Educator', salary: 62000, edu: 'Education degree (4 yrs) + state certification' },
    ],
  },
  {
    id: 'education_social',
    label: 'Education & Social Impact',
    emoji: '🌱',
    careers: [
      { name: 'School Principal', salary: 110000, edu: "Master's in Educational Leadership + teaching experience" },
      { name: 'School Counselor', salary: 70000, edu: "Master's in School Counseling + state license" },
      { name: 'College Professor', salary: 110000, edu: "Bachelor's + Master's + PhD in your field" },
      { name: 'Social Worker', salary: 62000, edu: "Bachelor's in Social Work (BSW) or Master's (MSW)" },
      { name: 'Youth Mentor', salary: 55000, edu: 'Social work/psychology/education degree' },
      { name: 'Nonprofit Director', salary: 90000, edu: "Bachelor's in Nonprofit Mgmt + Master's (helpful)" },
      { name: 'Life Coach', salary: 120000, edu: 'ICF coaching certification' },
      { name: 'Academic Advisor', salary: 57000, edu: "Bachelor's in Education/Counseling" },
      { name: 'Childcare Center Owner', salary: 90000, edu: 'Early childhood education + state licensing' },
    ],
  },
  {
    id: 'finance',
    label: 'Finance',
    emoji: '💰',
    careers: [
      { name: 'Financial Advisor / Banker', salary: 130000, edu: 'Finance, Economics, or Business degree + CFP cert' },
    ],
  },
  {
    id: 'healthcare',
    label: 'Healthcare',
    emoji: '🏥',
    careers: [
      { name: 'Doctor / Physician', salary: 275000, edu: '4-yr college + 4-yr med school + 3–7 yr residency' },
      { name: 'Nurse / Nurse Practitioner', salary: 90000, edu: '2-yr ADN or 4-yr BSN + NCLEX exam' },
      { name: 'OB-GYN', salary: 300000, edu: '4-yr college + 4-yr med school + 4-yr OB-GYN residency' },
      { name: 'Dentist', salary: 250000, edu: '4-yr pre-dental + 4-yr dental school (DDS/DMD)' },
      { name: 'Orthodontist', salary: 300000, edu: '4-yr college + 4-yr dental school + 2–3 yr residency' },
      { name: 'Pharmacist', salary: 140000, edu: '4-yr pre-pharmacy + 4-yr PharmD + NAPLEX exam' },
      { name: 'Physical Therapist', salary: 92000, edu: "Bachelor's in health sciences + Doctor of PT (DPT)" },
      { name: 'Occupational Therapist', salary: 90000, edu: "Bachelor's in health sciences + Master's in OT" },
      { name: 'Ultrasound Technician', salary: 80000, edu: "Associate's or Bachelor's in Diagnostic Sonography" },
      { name: 'Radiology Technician', salary: 75000, edu: "Associate's in Radiologic Technology (2 years)" },
      { name: 'Speech Pathologist', salary: 87000, edu: "Bachelor's in Communication Sciences + Master's" },
      { name: 'Nutritionist / Dietitian', salary: 75000, edu: "Bachelor's in Nutrition/Dietetics + RD exam" },
      { name: 'Medical Assistant', salary: 45000, edu: 'Medical assistant program (1 year) + CMA cert' },
    ],
  },
  {
    id: 'law',
    label: 'Law',
    emoji: '⚖️',
    careers: [
      { name: 'Lawyer / Attorney', salary: 160000, edu: '4-yr college + 3-yr law school (JD) + Bar Exam' },
    ],
  },
  {
    id: 'law_justice',
    label: 'Law & Justice',
    emoji: '🔍',
    careers: [
      { name: 'Judge', salary: 175000, edu: 'Law degree + bar exam + years of legal experience' },
      { name: 'Police Officer', salary: 75000, edu: 'Police academy + high school diploma minimum' },
      { name: 'FBI Agent', salary: 95000, edu: "Bachelor's degree + 3+ yrs experience + FBI Academy" },
      { name: 'Probation Officer', salary: 62000, edu: "Bachelor's in Criminal Justice/Social Work" },
      { name: 'Forensic Scientist', salary: 77000, edu: "Bachelor's in Forensic Science/Chemistry/Biology" },
      { name: 'Paralegal', salary: 62000, edu: "Associate's or Bachelor's in Paralegal Studies" },
      { name: 'Criminologist', salary: 75000, edu: "Bachelor's in Criminology + Master's/PhD for research" },
      { name: 'Political Strategist', salary: 150000, edu: 'Political Science, Communications, or Law degree' },
    ],
  },
  {
    id: 'media',
    label: 'Media',
    emoji: '📱',
    careers: [
      { name: 'Media / Content Creator', salary: 80000, edu: 'Communications/Media degree (optional) + build audience' },
    ],
  },
  {
    id: 'mental_health',
    label: 'Mental Health',
    emoji: '🧠',
    careers: [
      { name: 'Psychologist / Therapist', salary: 95000, edu: 'Psychology degree + Master\'s + Doctoral for psychologist' },
    ],
  },
  {
    id: 'science',
    label: 'Science',
    emoji: '🔬',
    careers: [
      { name: 'Scientist / Researcher', salary: 95000, edu: 'Science degree (Biology/Chemistry/Physics) + PhD' },
    ],
  },
  {
    id: 'tech_digital',
    label: 'Tech & Digital',
    emoji: '💻',
    careers: [
      { name: 'UX Designer', salary: 112000, edu: 'Design/HCI degree or bootcamp + Figma portfolio' },
      { name: 'Graphic Designer', salary: 72000, edu: 'Graphic design degree or bootcamp + Adobe Suite' },
      { name: 'App Developer', salary: 120000, edu: 'CS degree or coding bootcamp' },
      { name: 'Data Analyst', salary: 97000, edu: "Bachelor's in Statistics/Math/CS + SQL/Python/Tableau" },
      { name: 'Cybersecurity Analyst', salary: 120000, edu: 'CS/cybersecurity degree + CompTIA Security+' },
      { name: 'Social Media Manager', salary: 72000, edu: 'Marketing/Communications degree (optional)' },
      { name: 'Digital Marketer', salary: 90000, edu: 'Marketing degree or Google/Meta certifications' },
      { name: 'Content Creator', salary: 80000, edu: 'Start creating now — learn video editing' },
      { name: 'Video Editor', salary: 82000, edu: 'Film/media production + Premiere Pro/Final Cut' },
      { name: 'Web Designer', salary: 85000, edu: 'Web design bootcamp + HTML/CSS/Figma' },
      { name: 'AI Prompt Engineer', salary: 120000, edu: 'AI/prompt engineering courses + build a portfolio' },
      { name: 'Game Designer', salary: 100000, edu: 'Game design or CS degree + Unity/Unreal Engine' },
    ],
  },
  {
    id: 'technology',
    label: 'Technology',
    emoji: '🖥️',
    careers: [
      { name: 'Software Engineer / Tech', salary: 160000, edu: 'CS degree or coding bootcamp (2–4 years)' },
    ],
  },
  {
    id: 'trades',
    label: 'Trades & Entrepreneurship',
    emoji: '🔧',
    careers: [
      { name: 'Electrician', salary: 87000, edu: 'Electrician apprenticeship (4–5 years) + journeyman license' },
      { name: 'Welder', salary: 72000, edu: 'Welding certificate program (6 months–2 years) + AWS cert' },
      { name: 'Truck Driver / Owner Operator', salary: 90000, edu: 'CDL (Commercial Driver\'s License) training (3–7 weeks)' },
      { name: 'Interior Designer', salary: 100000, edu: 'Interior Design degree (4 years) + NCIDQ certification' },
      { name: 'Realtor / Property Investor', salary: 120000, edu: 'Real estate license (3–6 months) + join brokerage' },
      { name: 'Construction Project Manager', salary: 112000, edu: 'Construction Management or Civil Engineering degree' },
    ],
  },
];

export const LIFESTYLE_CATEGORIES = [
  {
    id: 'home',
    label: 'Dream Home',
    emoji: '🏠',
    options: [
      { label: 'Apartment (1BR)', cost: 1200 },
      { label: 'Apartment (2BR)', cost: 1800 },
      { label: 'Townhouse', cost: 2500 },
      { label: 'Single Family Home', cost: 3200 },
      { label: 'Luxury Home', cost: 5000 },
    ],
  },
  {
    id: 'car',
    label: 'Dream Car',
    emoji: '🚗',
    options: [
      { label: 'No Car / Public Transit', cost: 100 },
      { label: 'Used Car', cost: 350 },
      { label: 'New Car (mid-range)', cost: 500 },
      { label: 'Luxury Car', cost: 900 },
      { label: 'Exotic Car', cost: 2000 },
    ],
  },
  {
    id: 'travel',
    label: 'Travel',
    emoji: '✈️',
    options: [
      { label: 'Domestic trips only', cost: 100 },
      { label: '1 international trip/year', cost: 250 },
      { label: '2-3 trips/year', cost: 500 },
      { label: 'Frequent traveler (4+/year)', cost: 1000 },
      { label: 'Luxury world traveler', cost: 2500 },
    ],
  },
  {
    id: 'fashion',
    label: 'Fashion & Shopping',
    emoji: '👗',
    options: [
      { label: 'Budget shopping', cost: 100 },
      { label: 'Mid-range brands', cost: 300 },
      { label: 'Designer pieces', cost: 600 },
      { label: 'Full designer wardrobe', cost: 1500 },
    ],
  },
  {
    id: 'wellness',
    label: 'Wellness & Self-Care',
    emoji: '🧘',
    options: [
      { label: 'Basic (gym + haircare)', cost: 150 },
      { label: 'Standard (spa + gym)', cost: 350 },
      { label: 'Premium (trainer + spa)', cost: 700 },
      { label: 'Luxury wellness lifestyle', cost: 1500 },
    ],
  },
  {
    id: 'giving',
    label: 'Giving & Charity',
    emoji: '💝',
    options: [
      { label: 'Small donations', cost: 50 },
      { label: 'Regular giving (5%)', cost: 200 },
      { label: 'Generous giver (10%)', cost: 500 },
      { label: 'Philanthropist (20%+)', cost: 1500 },
    ],
  },
];

export const KIDS_OPTIONS = [
  { label: 'No kids', value: 0, cost: 0 },
  { label: '1 child', value: 1, cost: 1200 },
  { label: '2 children', value: 2, cost: 2200 },
  { label: '3 children', value: 3, cost: 3000 },
  { label: '4+ children', value: 4, cost: 3700 },
];

export const CAREER_MATCH = {
  budget: {
    label: 'Budget',
    range: '< $2,500/mo',
    careers: [
      { name: 'Teacher / Educator', salary: '$62K/yr', path: "Bachelor's + Cert" },
      { name: 'Social Worker (LCSW)', salary: '$65K/yr', path: "Master's Degree" },
      { name: 'Nurse (RN)', salary: '$82K/yr', path: 'BSN (4 yrs)' },
      { name: 'Dental Hygienist', salary: '$80K/yr', path: "Associate's (2 yrs)" },
      { name: 'Real Estate Agent', salary: '$80K/yr', path: 'License (months)' },
    ],
  },
  moderate: {
    label: 'Moderate',
    range: '$2,500–$5,000/mo',
    careers: [
      { name: 'Pharmacist', salary: '$128K/yr', path: 'PharmD (6 yrs)' },
      { name: 'Software Engineer', salary: '$130K/yr', path: 'CS Degree (4 yrs)' },
      { name: 'Nurse Practitioner', salary: '$115K/yr', path: "Master's (6 yrs)" },
      { name: 'Entrepreneur / CEO', salary: '$150K+/yr', path: 'Varies' },
      { name: 'Real Estate Investor', salary: '$120K/yr', path: 'Self-taught' },
      { name: 'Lawyer / Attorney', salary: '$135K/yr', path: 'Law School (7 yrs)' },
    ],
  },
  luxury: {
    label: 'Luxury',
    range: '$5,000–$9,000/mo',
    careers: [
      { name: 'Pharmacist', salary: '$128K/yr', path: 'PharmD (6 yrs)' },
      { name: 'Software Engineer', salary: '$130K/yr', path: 'CS Degree (4 yrs)' },
      { name: 'Lawyer / Attorney', salary: '$135K/yr', path: 'Law School (7 yrs)' },
      { name: 'CRNA (Nurse Anesthetist)', salary: '$200K+/yr', path: "Master's (7 yrs)" },
      { name: 'Entrepreneur / CEO', salary: '$150K+/yr', path: 'Varies' },
      { name: 'AI / ML Engineer', salary: '$160K/yr', path: 'CS Degree (4 yrs)' },
    ],
  },
  elite: {
    label: 'Elite',
    range: '> $9,000/mo',
    careers: [
      { name: 'Surgeon', salary: '$350K/yr', path: 'Medical + Residency (12 yrs)' },
      { name: 'Anesthesiologist', salary: '$330K/yr', path: 'Medical + Residency (12 yrs)' },
      { name: 'Radiologist', salary: '$315K/yr', path: 'Medical + Residency (12 yrs)' },
      { name: 'Investment Banker', salary: '$180K/yr', path: 'Finance Degree (4 yrs)' },
      { name: 'Venture Capitalist', salary: '$200K+/yr', path: 'MBA + Finance' },
      { name: 'Entrepreneur / CEO', salary: '$150K+/yr', path: 'Varies' },
      { name: 'Tax Attorney', salary: '$160K/yr', path: 'Law School + LLM (8 yrs)' },
    ],
  },
};

export const GLOW_ROADMAP = [
  {
    age: 'Age 15–18',
    label: 'Plant Your Seeds',
    emoji: '🌱',
    color: '#22c55e',
    steps: [
      'Focus on grades — GPA opens doors to scholarships',
      'Research scholarships now (start a list!)',
      'Build confidence & communication skills',
      'Open a savings account & save any income',
      'Explore career options through shadowing & research',
      'Start building your personal brand online',
    ],
  },
  {
    age: 'Age 18–22',
    label: 'Build Your Foundation',
    emoji: '🌸',
    color: '#a855f7',
    steps: [
      'College, trade school, or certification program',
      'Apply for every scholarship & grant available',
      'Land internships & part-time work in your field',
      'Build an emergency fund (3 months of expenses)',
      'Start a Roth IRA — even $50/mo compounds big',
      'Network intentionally — your circle = your net worth',
    ],
  },
  {
    age: 'Age 22–26',
    label: 'Level Up Your Income',
    emoji: '✨',
    color: '#818cf8',
    steps: [
      'Negotiate your first salary — never accept the first offer',
      'Max out employer 401k match (free money!)',
      'Pay down high-interest debt aggressively',
      'Start investing in index funds',
      'Build a side hustle or freelance income stream',
      'Learn real estate basics — homeownership is wealth',
    ],
  },
  {
    age: 'Age 26–30',
    label: 'Build Your Empire',
    emoji: '👑',
    color: '#f59e0b',
    steps: [
      'Buy your first home or investment property',
      'Diversify income: stocks, real estate, business',
      'Grow your career into leadership or ownership',
      'Give back — mentor younger girls',
      'Protect your wealth: life insurance, will, trust',
      'Live your dream life on YOUR terms 👑',
    ],
  },
];