export const CAT_META = {
  hygiene:          { label: 'Hygiene',              emoji: '🚿', labelColor: '#c084fc', cardBg: 'rgba(88,28,135,0.55)' },
  skincare:         { label: 'Skincare',              emoji: '✨', labelColor: '#c084fc', cardBg: 'rgba(88,28,135,0.55)' },
  budgeting:        { label: 'Budgeting',             emoji: '💰', labelColor: '#fb923c', cardBg: 'rgba(88,28,135,0.55)' },
  scholarships:     { label: 'Scholarships',          emoji: '🎓', labelColor: '#c084fc', cardBg: 'rgba(88,28,135,0.55)' },
  college:          { label: 'College',               emoji: '🏫', labelColor: '#c084fc', cardBg: 'rgba(60,40,100,0.6)' },
  entrepreneurship: { label: 'Entrepreneurship',      emoji: '🚀', labelColor: '#fb923c', cardBg: 'rgba(100,20,20,0.55)' },
  interview:        { label: 'Interview Prep',        emoji: '💼', labelColor: '#34d399', cardBg: 'rgba(6,78,59,0.5)' },
  safety:           { label: 'Safety',                emoji: '🛡️', labelColor: '#f87171', cardBg: 'rgba(127,29,29,0.5)' },
  studying:         { label: 'Studying',              emoji: '📖', labelColor: '#c084fc', cardBg: 'rgba(88,28,135,0.55)' },
  black_hair:       { label: 'Black Hair Care',       emoji: '👑', labelColor: '#c084fc', cardBg: 'rgba(88,28,135,0.55)' },
  mental_wellness:  { label: 'Mental Wellness',       emoji: '🧘‍♀️', labelColor: '#4ade80', cardBg: 'rgba(6,78,59,0.45)' },
  growth_mindset:   { label: 'Growth Mindset',        emoji: '🧠', labelColor: '#c084fc', cardBg: 'rgba(88,28,135,0.55)' },
  real_life:        { label: 'Real Life Skills',      emoji: '🗺️', labelColor: '#c084fc', cardBg: 'rgba(88,28,135,0.55)' },
  road_rules:       { label: 'Real Life Road Rules',  emoji: '🚗', labelColor: '#c084fc', cardBg: 'rgba(88,28,135,0.55)' },
  beauty:           { label: 'Beauty & Glow Up',      emoji: '💅', labelColor: '#f472b6', cardBg: 'rgba(131,24,67,0.45)' },
  character:        { label: 'Character & Values',    emoji: '💡', labelColor: '#c084fc', cardBg: 'rgba(88,28,135,0.55)' },
  life_skills:      { label: 'Life Skills',            emoji: '🏛️', labelColor: '#c084fc', cardBg: 'rgba(88,28,135,0.55)' },
  healthy_eating:   { label: 'Healthy Eating',         emoji: '🥗', labelColor: '#4ade80', cardBg: 'rgba(6,78,59,0.45)' },
  time_mgmt:        { label: 'Time Management',        emoji: '⏰', labelColor: '#c084fc', cardBg: 'rgba(88,28,135,0.55)' },
  adhd:             { label: 'ADHD',                   emoji: '⚡', labelColor: '#fbbf24', cardBg: 'rgba(120,53,15,0.5)' },
  caring_for_pets:  { label: 'Caring for Pets',        emoji: '🐾', labelColor: '#4ade80', cardBg: 'rgba(6,78,59,0.45)' },
  parenthood:       { label: 'Parenthood',             emoji: '👶', labelColor: '#f472b6', cardBg: 'rgba(131,24,67,0.45)' },
  good_parenting:   { label: 'Good Parenting',         emoji: '💝', labelColor: '#f472b6', cardBg: 'rgba(131,24,67,0.45)' },
  civic:             { label: 'Civic Education',         emoji: '🗳️', labelColor: '#818cf8', cardBg: 'rgba(49,46,129,0.55)' },
  community:         { label: 'Community & Discussion',   emoji: '💬', labelColor: '#34d399', cardBg: 'rgba(6,78,59,0.5)' },
  women_health:      { label: "Women's Health",            emoji: '🏥', labelColor: '#fb7185', cardBg: 'rgba(159,18,57,0.4)' },
  school_career:     { label: 'School & Career Skills',    emoji: '📚', labelColor: '#a3e635', cardBg: 'rgba(26,46,5,0.55)' },
  mindset_growth:    { label: 'Mindset & Growth',          emoji: '🌱', labelColor: '#fbbf24', cardBg: 'rgba(92,45,5,0.5)' },
};

export const RESOURCES = [
  { id: 1, cat: 'hygiene', emoji: '🚿', title: 'Daily Hygiene Routine',
    desc: 'Your complete guide to looking and feeling fresh every single day.',
    tips: ['Shower or bathe daily, especially after exercise', 'Brush teeth twice a day and floss daily', 'Use deodorant or antiperspirant every morning', 'Wash your face morning and night', 'Change underwear and socks daily', 'Wash your hair regularly (every 2–3 days or as needed for your hair type)'],
    quick_facts: [],
    actions: ['Build a 10-minute morning routine', 'Keep hygiene products organized in one place', 'Set phone reminders until it becomes habit'] },

  { id: 2, cat: 'hygiene', emoji: '🌸', title: 'Period Hygiene & Care',
    desc: 'Everything you need to know about managing your period with confidence.',
    tips: ['Change pads/tampons every 4–6 hours', 'Wear period underwear as backup protection', 'Track your cycle to be prepared', 'Stay hydrated and eat iron-rich foods', 'Use a heating pad for cramps', 'Talk to a doctor if periods are very painful or irregular'],
    quick_facts: ['Average period lasts 3–7 days', 'Normal cycle is 21–35 days', 'You can use the app\'s Cycle Tracker to monitor yours'],
    actions: ['Download a period tracking app', 'Build a period emergency kit for your bag', 'Talk to a trusted adult or doctor if you have unusual symptoms'] },

  { id: 3, cat: 'skincare', emoji: '✨', title: 'Skincare for Glowing Skin',
    desc: 'Simple skincare routines that actually work — no matter your skin type.',
    tips: ['Cleanse your face twice daily with a gentle cleanser', 'Always moisturize — even oily skin needs hydration', 'Wear SPF 30+ sunscreen every day (yes, even indoors)', 'Never sleep with makeup on', 'Don\'t pop pimples — it causes scarring', 'Drink water — hydration shows on your skin'],
    quick_facts: [],
    actions: ['Start with 3 products: cleanser, moisturizer, SPF', 'Introduce new products one at a time', 'Give products 4–6 weeks to show results'] },

  { id: 4, cat: 'skincare', emoji: '💆‍♀️', title: 'Managing Acne & Breakouts',
    desc: 'Acne is normal. Here\'s how to manage it without damaging your skin.',
    tips: ['Use salicylic acid or benzoyl peroxide for acne-prone skin', 'Keep your hands away from your face', 'Clean your phone screen regularly', 'Change pillowcases weekly', 'Reduce stress — it triggers breakouts', 'See a dermatologist for persistent acne'],
    quick_facts: ['85% of teens experience acne', 'Diet, stress, and hormones all affect skin', 'Most acne improves with consistent care'],
    actions: ['Try a salicylic acid cleanser for 4 weeks', 'Change your pillowcase 2x per week', 'See a dermatologist if OTC products don\'t work after 3 months'] },

  { id: 5, cat: 'budgeting', emoji: '💰', title: 'Budgeting 101',
    desc: 'Learn how to manage your money so your money doesn\'t manage you.',
    tips: ['Use the 50/30/20 rule: 50% needs, 30% wants, 20% savings', 'Track every dollar you spend for one week', 'Pay yourself first — save before you spend', 'Avoid impulse purchases — wait 24 hours before buying', 'Use cash envelopes or budgeting apps', 'Know the difference between needs and wants'],
    quick_facts: ['Starting to save at 16 vs 25 can mean $100K+ difference by retirement', 'Compound interest rewards those who start early'],
    actions: ['Open a savings account if you don\'t have one', 'Set a weekly spending limit', 'Save at least $5–$20 per week no matter what'] },

  { id: 6, cat: 'budgeting', emoji: '💼', title: 'Teen Side Hustles',
    desc: 'Real ways to make money right now — no degree required.',
    tips: ['Babysitting and pet sitting are always in demand', 'Sell handmade crafts on Etsy or local markets', 'Offer tutoring in subjects you\'re good at', 'Create content on social media and monetize', 'Offer lawn care, car washing, or cleaning services', 'Resell thrifted items online'],
    quick_facts: [],
    actions: ['Pick one hustle and start this week', 'Set a goal: earn $50 in the next 30 days', 'Open a separate account for hustle money'] },

  { id: 7, cat: 'scholarships', emoji: '🎓', title: 'Finding Scholarships',
    desc: 'Free money for college exists — you just have to find it and apply.',
    tips: ['Start searching in 9th or 10th grade', 'Apply for local scholarships — less competition', 'Check Fastweb, Scholarships.com, and Bold.org', 'Write a strong personal essay — it\'s your competitive edge', 'Apply for everything — even small amounts add up', 'Keep a spreadsheet of deadlines'],
    quick_facts: ['Over $46 billion in scholarships is available each year', 'Many scholarships go unclaimed because no one applies', 'You don\'t have to have a 4.0 GPA — many are need-based or essay-based'],
    actions: ['Create a scholarship search account on Fastweb.com', 'Ask your school counselor about local scholarships', 'Set aside time each week to apply'] },

  { id: 8, cat: 'college', emoji: '🏫', title: 'College Prep Guide',
    desc: 'Everything you need to know to get into the college of your dreams.',
    tips: ['Take challenging classes (AP, IB, dual enrollment)', 'Get involved in extracurriculars that align with your goals', 'Build relationships with teachers for recommendation letters', 'Prepare for SAT/ACT early — take practice tests', 'Visit campuses virtually or in person', 'Apply to a mix of reach, match, and safety schools'],
    quick_facts: ['Most colleges look at GPA, test scores, essays, activities, and recommendations', 'Community college is a smart, affordable path too'],
    actions: ['Create a college list by junior year', 'Take the PSAT in 10th grade', 'Start your Common App essay early in senior year'] },

  { id: 9, cat: 'entrepreneurship', emoji: '🚀', title: 'Starting Your Own Business',
    desc: 'You don\'t need to wait until you\'re an adult to be an entrepreneur.',
    tips: ['Start with a problem you want to solve', 'Test your idea before investing money', 'Build a simple website or social media presence', 'Learn basic business terms: revenue, profit, expenses', 'Find a mentor in business', 'Failure is part of the process — keep going'],
    quick_facts: ['Many successful CEOs started their first business as teenagers', 'You can register an LLC as a minor with a parent\'s help'],
    actions: ['Write a one-page business plan', 'Research your target customer', 'Start small and scale up'] },

  { id: 10, cat: 'interview', emoji: '💼', title: 'Interview Prep & Job Skills',
    desc: 'How to walk into any interview — job, college, scholarship — and own the room.',
    tips: ['Research the company or program before your interview', 'Prepare answers to common questions: "Tell me about yourself," "What are your strengths?"', 'Dress professionally — first impressions matter', 'Arrive 10 minutes early', 'Make eye contact and speak clearly', 'Send a thank-you email within 24 hours'],
    quick_facts: [],
    actions: ['Practice with a friend or in the mirror', 'Prepare 3 stories about your achievements', 'Write down 5 questions to ask the interviewer'] },

  { id: 11, cat: 'safety', emoji: '🛡️', title: 'Personal Safety',
    desc: 'Know your rights, trust your instincts, and always protect yourself.',
    tips: ['Always tell someone where you\'re going', 'Trust your gut — if something feels wrong, leave', 'Keep emergency contacts saved in your phone', 'Never share your location with strangers online', 'Know the signs of unhealthy relationships', 'It\'s always okay to say no — to anyone, for any reason'],
    quick_facts: ['Your body belongs to you — always', 'You have the right to feel safe everywhere you go', 'If you feel unsafe, call 911 or text 911 where available'],
    actions: ['Save ICE (In Case of Emergency) contacts in your phone', 'Share your location with a trusted person when going out', 'Know the number for the Crisis Text Line: Text HOME to 741741'] },

  { id: 96, cat: 'women_health', emoji: '🏥', title: 'Health Appointments for Girls & Women',
    desc: 'Your body deserves regular check-ins. Here is your guide.',
    tips: ['Annual wellness visit every year — even when you feel healthy', 'First gynecology visit recommended between ages 13–15', 'Dental cleanings every 6 months — gum disease is linked to heart disease', 'Mental health checkups are just as important as physical ones', 'Preventive care is covered at no cost under most health insurance plans', 'You have the right to ask questions and request a second opinion'],
    quick_facts: ['Pap smear starts at age 21. HPV vaccine recommended ages 9–26', 'FQHCs offer care on a sliding scale — many charge $0 for low-income patients', 'Planned Parenthood and school-based clinics offer free or low-cost care'],
    actions: ['Create a personal health calendar — schedule your annual wellness visit, dental cleaning, and eye exam.', 'Ask a trusted family member about your family health history and write it down.', 'If you lack insurance, research one free or low-cost clinic in your area this week.'] },

  { id: 97, cat: 'school_career', emoji: '📚', title: 'How to Be a Good Student',
    desc: 'School is your first job. Here is how to show up and win.',
    tips: ['Attendance matters — missing 2 days a month adds up to 18 days a year', 'Every phone check costs ~23 minutes of refocused attention', 'Active recall (quizzing yourself) beats re-reading every time', 'Sleep consolidates memory — do not sacrifice it for late-night cramming', 'Asking questions is a sign of intelligence, not weakness', 'Consistent effort beats talent every single time'],
    quick_facts: ['Students who set specific study goals perform significantly better', 'The Pomodoro Technique: 25 minutes focused + 5-minute break = more done in less time', 'Teachers are one of your most underused resources — office hours exist for a reason'],
    actions: ['Create a weekly study schedule and pick one subject to improve this week.', 'Try the Pomodoro Technique for your next study session and note how it affects focus.', 'Speak to one teacher outside of class this week — ask a question or ask for advice.'] },

  { id: 95, cat: 'mindset_growth', emoji: '🌱', title: 'Trust the Process',
    desc: 'Stop stressing about the future. Your season is coming.',
    tips: ['Shift focus from the destination to what you can do today', 'Planning is productive — worrying is unproductive. Know the difference.', 'You cannot control outcomes, but you can always control effort and attitude', 'Delayed gratification is one of the strongest predictors of long-term success', 'Track your inputs (did you show up, study, practice?) not just outputs', 'The girls who made it kept going when results were invisible'],
    quick_facts: ['Anxiety about the future activates the same brain response as physical danger', 'People who focus on process — not just outcome — perform better and feel happier', 'Social media is everyone else highlight reel — you are not behind. You are on your own timeline.'],
    actions: ['Write down one big goal and list 3–5 daily habits that move you toward it. Post it where you can see it.', 'Identify something you have been anxious about. Ask: can I act on this right now? If yes, write one step. If no, release it.', 'Research one person you admire — find out how long it took them to make it.'] },
];

export const RESOURCES_ALL = RESOURCES;

export const CIVIC_TOPICS = [
  {
    id: 'how_voting_works',
    category: 'How Voting Works',
    emoji: '🗳️',
    title: 'How Voting Works',
    desc: 'Your vote is your voice. Here\'s how to use it.',
    why_it_matters: 'Voting is one of the most direct ways citizens shape their communities. Understanding how it works empowers you to participate confidently.',
    key_facts: ['In the U.S., citizens can vote starting at age 18 in most elections.', 'You must register to vote before Election Day in most states.', 'Voting happens at local polling places or by mail/absentee ballot.', 'Elections happen at local, state, and national levels.'],
    sections: [
      { title: 'What Is Voting?', content: 'Voting is the process by which citizens choose their representatives and decide on important issues. In a democracy, elected officials are supposed to represent the people who voted for them. When more people vote, the results better reflect what the community actually wants.' },
      { title: 'Who Can Vote?', content: 'In the United States, you can vote if you are a U.S. citizen, at least 18 years old on Election Day, and registered to vote in your state. Some states allow 17-year-olds to vote in primaries if they will be 18 by the general election.' },
      { title: 'How Do You Register?', content: 'You can register to vote online at vote.gov, at your local DMV, at your school or library, or by mail. Registration deadlines vary by state — some require registration 30 days before an election, others allow same-day registration.' },
      { title: 'What Happens on Election Day?', content: 'On Election Day, you go to your assigned polling place (found at vote.gov), show your ID if required, receive a ballot, mark your choices privately, and submit your ballot. You can also vote early or by mail in many states.' },
      { title: 'Types of Elections', content: 'Primary elections determine which candidates represent each party. General elections are the main elections where winners are chosen. Local elections decide mayors, school boards, city councils, and judges. Midterm elections happen between presidential elections.' },
    ],
    activities: ['Find Your Polling Place: Visit vote.gov and look up where you would vote if you were 18 today.', 'Hold a mock election in your group on a fun topic — run a real voting process.', 'Research the top 3 reasons people give for not voting. Write a response to "my vote doesn\'t matter."'],
  },
];