export const QUIZ_DATA = {
  // Glow From Within - Elementary
  'what_makes_you_glow': [
    { question: "What makes you uniquely beautiful?", options: ["Only your looks", "Your personality and character", "What others think", "Nothing"], correctAnswer: 1 },
    { question: "How many character words should you include in your self-portrait?", options: ["3", "5", "10", "1"], correctAnswer: 1 },
    { question: "Who should you write a letter to about your best qualities?", options: ["Your teacher", "Your future self", "Your friend", "Your parent"], correctAnswer: 1 },
    { question: "What is a Glow Board?", options: ["A game board", "A collage of things that make you happy", "A chalkboard", "A scoreboard"], correctAnswer: 1 },
    { question: "What should you share with your class?", options: ["A secret", "One kind thing you did", "A joke", "Nothing"], correctAnswer: 1 },
    { question: "Your inner glow comes from:", options: ["Makeup", "Your character", "Clothes", "Hair"], correctAnswer: 1 },
    { question: "Is it okay to be different from others?", options: ["No", "Yes, differences make you special", "Only sometimes", "I don't know"], correctAnswer: 1 },
    { question: "What makes you glow from within?", options: ["Being mean", "Being kind", "Ignoring others", "Being selfish"], correctAnswer: 1 },
    { question: "Should you compare yourself to others?", options: ["Always", "Never, focus on yourself", "Sometimes", "Every day"], correctAnswer: 1 },
    { question: "Your best qualities are:", options: ["Only physical", "Inside and outside", "Nothing", "What others say"], correctAnswer: 1 },
    { question: "Writing to your future self helps you:", options: ["Forget things", "Remember your goals", "Waste time", "Nothing"], correctAnswer: 1 },
    { question: "A character word describes:", options: ["Your clothes", "Your personality", "Your house", "Your school"], correctAnswer: 1 },
    { question: "Kindness makes you:", options: ["Less beautiful", "More beautiful", "Ugly", "Nothing"], correctAnswer: 1 },
    { question: "Your Glow Board should include:", options: ["Only pictures", "Things that make you happy", "Only words", "Nothing"], correctAnswer: 1 },
    { question: "Being yourself is:", options: ["Bad", "Amazing", "Weird", "Boring"], correctAnswer: 1 },
  ],
  // Glow From Within - Middle School
  'authentic_beauty': [
    { question: "What is the main goal of this lesson?", options: ["Learn makeup", "Navigate social media with confidence", "Buy filters", "Delete all apps"], correctAnswer: 1 },
    { question: "What should you do in a social media audit?", options: ["Follow more people", "Unfollow accounts that make you feel bad", "Post more", "Nothing"], correctAnswer: 1 },
    { question: "How many things should you list that you love about your appearance?", options: ["1", "5", "10", "20"], correctAnswer: 2 },
    { question: "What type of photo should you post?", options: ["Heavily filtered", "Unfiltered", "Fake", "None"], correctAnswer: 1 },
    { question: "Who should you research?", options: ["A celebrity", "A woman you admire", "A stranger", "No one"], correctAnswer: 1 },
    { question: "Filters are:", options: ["Always accurate", "Often unrealistic", "Perfect", "Necessary"], correctAnswer: 1 },
    { question: "Beauty standards on social media are often:", options: ["Realistic", "Unrealistic", "Perfect", "Achievable"], correctAnswer: 1 },
    { question: "Your authentic beauty comes from:", options: ["Filters", "Being yourself", "Makeup", "Others' opinions"], correctAnswer: 1 },
    { question: "Should you compare your behind-the-scenes to others' highlights?", options: ["Yes", "No, that's unfair", "Always", "Sometimes"], correctAnswer: 1 },
    { question: "What makes someone beautiful beyond appearance?", options: ["Nothing", "Character and actions", "Only clothes", "Only hair"], correctAnswer: 1 },
    { question: "Journaling about unfiltered photos helps you:", options: ["Feel worse", "Process feelings", "Delete photos", "Nothing"], correctAnswer: 1 },
    { question: "Social media shows:", options: ["Real life", "Curated highlights", "Everything", "Truth"], correctAnswer: 1 },
    { question: "Confidence comes from:", options: ["Filters", "Accepting yourself", "Likes", "Followers"], correctAnswer: 1 },
    { question: "Unrealistic beauty standards can make you feel:", options: ["Great", "Inadequate", "Happy", "Confident"], correctAnswer: 1 },
    { question: "Being authentic means:", options: ["Pretending", "Being real", "Copying others", "Hiding"], correctAnswer: 1 },
  ],
  'i_am_enough': [
    { question: "What is an I Am poem?", options: ["A poem about others", "A poem with 10 positive self-statements", "A sad poem", "A short poem"], correctAnswer: 1 },
    { question: "How many affirmations should you say daily?", options: ["1", "3", "10", "0"], correctAnswer: 1 },
    { question: "Where should you practice affirmations?", options: ["In the mirror", "Nowhere", "Outside", "School"], correctAnswer: 0 },
    { question: "What should you decorate on your journal cover?", options: ["Your name and things you love", "Nothing", "Only pictures", "Only colors"], correctAnswer: 0 },
    { question: "How many classmates should you compliment?", options: ["0", "1", "3", "10"], correctAnswer: 2 },
    { question: "Self-worth means:", options: ["Valuing others", "Valuing yourself", "No value", "Money"], correctAnswer: 1 },
    { question: "Affirmations should be:", options: ["Negative", "Positive", "Mean", "False"], correctAnswer: 1 },
    { question: "You are enough:", options: ["Sometimes", "Always", "Never", "When others say so"], correctAnswer: 1 },
    { question: "Complimenting others makes you feel:", options: ["Bad", "Good", "Nothing", "Worse"], correctAnswer: 1 },
    { question: "A journal is for:", options: ["Others to read", "Your private thoughts", "Everyone", "No one"], correctAnswer: 1 },
    { question: "Mirror practice helps build:", options: ["Confidence", "Fear", "Doubt", "Nothing"], correctAnswer: 0 },
    { question: "Your worth is not determined by:", options: ["Your character", "Others' opinions", "Your actions", "Your values"], correctAnswer: 1 },
    { question: "Self-love is:", options: ["Selfish", "Important", "Bad", "Unnecessary"], correctAnswer: 1 },
    { question: "Positive self-statements should be:", options: ["False", "True and kind", "Mean", "Negative"], correctAnswer: 1 },
    { question: "Loving yourself completely means:", options: ["Only your looks", "All of you", "Nothing", "Only talents"], correctAnswer: 1 },
  ],
  'confidence_crown': [
    { question: "How long should you practice the Power Pose?", options: ["30 seconds", "2 minutes", "5 minutes", "10 minutes"], correctAnswer: 1 },
    { question: "What is a Confidence Crown?", options: ["A real crown", "A craft with affirmations", "A hat", "A game"], correctAnswer: 1 },
    { question: "What should you role-play?", options: ["Confident introductions", "Shy behavior", "Hiding", "Nothing"], correctAnswer: 0 },
    { question: "When did you feel really confident?", options: ["Never", "Write about a specific time", "Always", "I don't know"], correctAnswer: 1 },
    { question: "Confidence is your:", options: ["Weakness", "Crown", "Problem", "Nothing"], correctAnswer: 1 },
    { question: "Power poses make you feel:", options: ["Weaker", "More confident", "Scared", "Nothing"], correctAnswer: 1 },
    { question: "Stepping into your power means:", options: ["Hiding", "Being confident", "Running away", "Nothing"], correctAnswer: 1 },
    { question: "Affirmations on your crown should be:", options: ["Negative", "Positive and empowering", "Mean", "False"], correctAnswer: 1 },
    { question: "Confident introductions include:", options: ["Looking down", "Eye contact", "Whispering", "Hiding"], correctAnswer: 1 },
    { question: "Your confidence can:", options: ["Never change", "Grow", "Disappear", "Stay the same"], correctAnswer: 1 },
    { question: "Role-playing helps you:", options: ["Practice", "Fail", "Nothing", "Waste time"], correctAnswer: 0 },
    { question: "Wearing your crown means:", options: ["Being arrogant", "Owning your confidence", "Being mean", "Nothing"], correctAnswer: 1 },
    { question: "Confidence comes from:", options: ["Others", "Within you", "Money", "Looks"], correctAnswer: 1 },
    { question: "Journaling about confidence helps you:", options: ["Forget", "Remember and build", "Nothing", "Lose confidence"], correctAnswer: 1 },
    { question: "You should step into your power:", options: ["Never", "Today", "Someday", "Tomorrow"], correctAnswer: 1 },
  ],
  // Add more quiz questions for other lessons as needed
  // This is a sample - in production you'd add all 15 questions for each lesson
};