import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import AppBackground from '@/components/AppBackground';
import BottomNav from '@/components/BottomNav';
import LibraryQuiz from '@/components/LibraryQuiz';
import QUIZZES from '@/lib/libraryQuizzes';
import { BookOpen, ChevronLeft } from 'lucide-react';

const SECTION_TABS = [
  { id: 'resources', label: 'Resources', emoji: '📚' },
  { id: 'book_club', label: 'Book Club', emoji: '📖' },
  { id: 'glow_reads', label: 'Glow Reads', emoji: '✨' },
  { id: 'recommended', label: 'Recommended', emoji: '⭐' },
  { id: 'audiobooks', label: 'Audiobooks', emoji: '🎧' },
  { id: 'faith', label: 'Faith & Inspiration', emoji: '🙏' },
  { id: 'career', label: 'Career & Business', emoji: '💼' },
  { id: 'confidence', label: 'Confidence & Healing', emoji: '💜' },
  { id: 'teen_reads', label: 'Teen Reads', emoji: '📕' },
  { id: 'college', label: 'College & Adulting', emoji: '🎓' },
  { id: 'journals', label: 'Journals & Workbooks', emoji: '📓' },
  { id: 'your_voice', label: 'Your Voice', emoji: '🎤' },
];

const CATEGORIES = [
  { id: 'all', label: 'All', emoji: '' },
  { id: 'hygiene', label: 'Hygiene', emoji: '🚿' },
  { id: 'skincare', label: 'Skincare', emoji: '✨' },
  { id: 'budgeting', label: 'Budgeting', emoji: '💰' },
  { id: 'scholarships', label: 'Scholarships', emoji: '🎓' },
  { id: 'college', label: 'College', emoji: '🏢' },
  { id: 'entrepreneurship', label: 'Entrepreneurship', emoji: '🚀' },
  { id: 'interview', label: 'Interview Prep', emoji: '💼' },
  { id: 'safety', label: 'Safety', emoji: '🛡️' },
  { id: 'studying', label: 'Studying', emoji: '📖' },
  { id: 'black_hair', label: 'Black Hair Care', emoji: '👑' },
  { id: 'mental_wellness', label: 'Mental Wellness', emoji: '🧘‍♀️' },
  { id: 'growth_mindset', label: 'Growth Mindset', emoji: '🧠' },
  { id: 'real_life', label: 'Real Life Skills', emoji: '🗺️' },
  { id: 'road_rules', label: 'Real Life Road Rules', emoji: '🚗' },
  { id: 'beauty', label: 'Beauty & Glow Up', emoji: '💅' },
  { id: 'character', label: 'Character & Values', emoji: '💡' },
  { id: 'life_skills', label: 'Life Skills', emoji: '🏛️' },
  { id: 'healthy_eating', label: 'Healthy Eating', emoji: '🥗' },
  { id: 'time_mgmt', label: 'Time Management', emoji: '⏰' },
];

const RESOURCES = [
  // Hygiene
  { id: 1, cat: 'hygiene', emoji: '🚿', title: 'Daily Hygiene Routine', desc: 'Your complete guide to looking and feeling fresh every single day.', content: `**Why Hygiene Matters**\nYour daily hygiene routine is the foundation of confidence. When you feel clean and fresh, you carry yourself differently.\n\n**Morning Routine**\n• Wash your face with a gentle cleanser\n• Brush teeth for 2 minutes (morning & night)\n• Deodorant — apply to clean, dry skin\n• Shower or freshen up daily\n• Change into clean clothes\n\n**Body Care**\n• Shower daily or every other day\n• Use a body wash that suits your skin type\n• Moisturize your skin while it's still slightly damp\n• Wash hands regularly, especially before eating\n\n**Dental Care**\n• Brush twice a day, floss once\n• Use mouthwash for extra freshness\n• See a dentist every 6 months\n\n**Hair Care Basics**\n• Wash hair based on your hair type (1-3x per week)\n• Keep a clean brush/comb\n• Avoid touching your hair too much\n\n**Quick Tips**\n✨ Keep travel-sized products in your bag for refreshing on the go\n✨ Change your pillowcase weekly — your skin will thank you\n✨ Drink water — hydration shows on your skin` },
  { id: 2, cat: 'hygiene', emoji: '🌸', title: 'Period Hygiene & Care', desc: 'Everything you need to know about managing your period with confidence.', content: `**Your Period is Power**\nYour cycle is a sign that your body is working perfectly. Managing it confidently starts with the right information.\n\n**Products to Know**\n• **Pads** — Easy to use, great for starting out. Change every 4-6 hours.\n• **Tampons** — Internal option. Never leave in more than 8 hours (TSS risk).\n• **Menstrual Cup** — Reusable, eco-friendly, lasts 10+ years.\n• **Period Underwear** — Comfortable backup protection.\n\n**Changing Your Products**\n• Change pads every 4-6 hours, or sooner if needed\n• Change tampons every 4-8 hours — set a phone reminder\n• Always wash hands before and after\n\n**Managing Cramps**\n• Heating pad on your lower abdomen\n• Ibuprofen works best when taken early\n• Light movement and yoga help\n• Magnesium-rich foods (dark chocolate, bananas)\n\n**Period Kit for School**\n🎒 Pack in a small pouch: 2-3 pads or tampons, pain reliever, wipes, backup underwear\n\n**When to See a Doctor**\n🚨 Periods lasting 10+ days, extreme pain, soaking a pad per hour, or no period for 3+ months` },

  // Skincare
  { id: 3, cat: 'skincare', emoji: '✨', title: 'Skincare for Glowing Skin', desc: 'Simple skincare routines that actually work — no matter your skin type.', content: `**Know Your Skin Type**\n• **Oily** — Shiny, enlarged pores, prone to breakouts\n• **Dry** — Tight, flaky, dull\n• **Combination** — Oily T-zone, dry cheeks\n• **Normal** — Balanced, minimal issues\n• **Sensitive** — Easily irritated, reacts to products\n\n**The Basic Routine (Everyone Needs This)**\n\n**Morning:**\n1. Gentle cleanser\n2. Moisturizer\n3. SPF (sunscreen protects from aging and cancer)\n\n**Evening:**\n1. Remove makeup (micellar water or cleansing balm)\n2. Cleanser\n3. Treatment (if needed — niacinamide, retinol, etc.)\n4. Moisturizer\n\n**Drugstore Heroes**\n• CeraVe Hydrating Cleanser\n• Neutrogena Hydro Boost Moisturizer\n• La Roche-Posay SPF 50\n• The Ordinary Niacinamide 10%\n\n**Glow Tips**\n✨ Drink 8+ glasses of water daily\n✨ Change pillowcase weekly\n✨ Never sleep in makeup\n✨ Sunscreen is non-negotiable — even on cloudy days` },
  { id: 4, cat: 'skincare', emoji: '💆‍♀️', title: 'Managing Acne & Breakouts', desc: 'Acne is normal. Here\'s how to manage it without damaging your skin.', content: `**Acne is Normal — You Are Not Alone**\nOver 85% of teens experience acne. It is not a sign of being dirty or unhealthy. It is hormones, genetics, and sometimes lifestyle.\n\n**What Causes Acne**\n• Excess oil production\n• Bacteria (C. acnes)\n• Clogged pores from dead skin cells\n• Hormonal changes\n• Touching your face\n\n**What Actually Works**\n• **Salicylic Acid** — Unclogs pores, great for blackheads\n• **Benzoyl Peroxide** — Kills bacteria, reduces inflammation\n• **Niacinamide** — Reduces redness and oil\n• **Retinol** — Speeds up cell turnover (start slow!)\n\n**What to Avoid**\n🚫 Popping pimples — causes scarring and more breakouts\n🚫 Over-washing — strips skin and causes rebound oil\n🚫 Heavy, comedogenic products\n🚫 Touching your face throughout the day\n\n**See a Dermatologist If:**\n• OTC products aren't working after 3 months\n• You have deep, painful cystic acne\n• Acne is affecting your mental health\n\n**Quick Tip:** Change your pillowcase 2x per week and clean your phone screen daily — both touch your face constantly.` },

  // Budgeting
  { id: 5, cat: 'budgeting', emoji: '💰', title: 'Budgeting 101', desc: 'Learn how to manage your money so your money doesn\'t manage you.', content: `**Why Budgeting Matters Now**\nThe habits you build today will shape your financial future. You don't need to earn a lot to start budgeting — you just need to start.\n\n**The 50/30/20 Rule**\n• **50%** — Needs (essentials: food, transportation, necessities)\n• **30%** — Wants (fun, clothes, entertainment)\n• **20%** — Savings & goals\n\n**Step 1: Know Your Income**\nWrite down everything that comes in — allowance, job, gifts.\n\n**Step 2: Track Your Spending**\nFor one week, write down every single purchase. You will be surprised.\n\n**Step 3: Set a Savings Goal**\nWhat are you saving for? A phone? A car? College? Name it.\n\n**Budgeting Apps for Teens**\n• YNAB (You Need A Budget)\n• Mint\n• Greenlight (teens + parents)\n• Just a notes app works too!\n\n**Money Mindset**\n💡 Pay yourself first — save before you spend\n💡 Wants vs. needs: ask "do I need this or just want it?"\n💡 Every dollar you save now grows over time with compound interest` },
  { id: 6, cat: 'budgeting', emoji: '💼', title: 'Teen Side Hustles', desc: 'Real ways to make money right now — no degree required.', content: `**You Can Start Making Money Now**\nYou don't have to wait until you're 18 or have a degree to start earning.\n\n**Service-Based Hustles**\n• Babysitting & childcare\n• Dog walking & pet sitting\n• Lawn mowing & yard work\n• Car washing\n• House cleaning\n• Grocery shopping for neighbors\n\n**Skills-Based Hustles**\n• Tutoring classmates\n• Social media management for local businesses\n• Graphic design (Canva is free!)\n• Selling photos you take\n• Video editing\n\n**Online Hustles**\n• Sell handmade items on Etsy\n• Resell thrifted clothes on Depop/Poshmark\n• Sell digital products (templates, notes)\n• YouTube or TikTok content\n\n**Getting Started**\n1. Pick ONE hustle to start with\n2. Tell your neighborhood/network\n3. Set a fair price\n4. Deliver great work and ask for referrals\n\n💡 Track your earnings and save at least 20% of everything you make` },

  // Scholarships
  { id: 7, cat: 'scholarships', emoji: '🎓', title: 'Finding Scholarships', desc: 'Free money for college exists — you just have to find it and apply.', content: `**Scholarships Are Free Money**\nMillions of dollars in scholarship money goes unclaimed every year because students don't apply. That stops today.\n\n**Where to Search**\n• Fastweb.com\n• Scholarships.com\n• Bold.org\n• Going Merry\n• Your state's department of education\n• Local community foundations\n• Your high school counselor's office\n\n**Types of Scholarships**\n• Merit-based (grades, test scores)\n• Need-based (financial situation)\n• Identity-based (race, gender, first-generation)\n• Essay-based (write your story)\n• Community service\n• Sports & extracurriculars\n\n**Application Tips**\n✅ Start early — junior year of high school\n✅ Apply to small local scholarships (less competition!)\n✅ Customize each essay — never use a generic one\n✅ Get multiple people to proofread\n✅ Track deadlines in a spreadsheet\n✅ Apply to everything — even $500 adds up\n\n**FAFSA First**\nFill out the FAFSA (Free Application for Federal Student Aid) as soon as it opens — October 1st of your senior year.` },

  // College
  { id: 8, cat: 'college', emoji: '🏫', title: 'College Prep Guide', desc: 'Everything you need to know to get into the college of your dreams.', content: `**Start Earlier Than You Think**\nCollege prep isn't just for seniors. What you do in 9th and 10th grade matters too.\n\n**The College Application Timeline**\n**9th-10th Grade:** Take challenging classes, explore interests, join clubs\n**11th Grade:** PSAT, begin college research, visit campuses (virtual counts)\n**Summer Before 12th:** Draft essays, request recommendation letters\n**12th Grade (Fall):** Apply! Common App opens August 1st\n**12th Grade (Winter/Spring):** FAFSA, financial aid letters, decide by May 1st\n\n**What Colleges Look For**\n• GPA and course rigor\n• Standardized test scores (SAT/ACT) — many schools are test-optional now\n• Extracurriculars and leadership\n• Essays — your unique voice matters most\n• Recommendation letters\n• Community service\n\n**Essay Tips**\n✍️ Write about something specific, not general\n✍️ Show who you are, not just what you did\n✍️ Start with a compelling hook\n✍️ Be authentic — don't try to sound impressive\n\n**Apply to a Range**\nSafety schools + match schools + reach schools = balanced list` },

  // Entrepreneurship
  { id: 9, cat: 'entrepreneurship', emoji: '🚀', title: 'Starting Your Own Business', desc: 'You don\'t need to wait until you\'re an adult to be an entrepreneur.', content: `**You Are Already an Entrepreneur at Heart**\nEvery business started as an idea. Your age is not a barrier — your mindset is the only thing that matters.\n\n**Business Ideas for Teen Girls**\n• Handmade jewelry or accessories\n• Custom clothing or thrifted fashion\n• Tutoring or educational services\n• Social media management\n• Event planning\n• Baking & custom treats\n• Photography or videography\n\n**The Simple Business Plan**\n1. **What** — What product or service are you selling?\n2. **Who** — Who is your customer?\n3. **How Much** — What's your price? What are your costs?\n4. **How** — How will you reach customers?\n\n**Starting Steps**\n✅ Research your idea (is there demand?)\n✅ Start small — test before investing big\n✅ Open a separate savings account for business money\n✅ Create a simple Instagram or Etsy page\n✅ Tell 10 people about your business\n\n**Teen Entrepreneur Resources**\n• SCORE Mentoring (free mentors)\n• Young Entrepreneurs Academy\n• Shark Tank Junior\n\n💡 The best time to start is before you feel ready.` },

  // Interview Prep
  { id: 10, cat: 'interview', emoji: '💼', title: 'Interview Prep & Job Skills', desc: 'How to walk into any interview — job, college, scholarship — and own the room.', content: `**Confidence is a Skill You Can Build**\nEvery great interviewer was once a nervous first-timer. Practice makes perfect.\n\n**Before the Interview**\n• Research the company or program\n• Prepare answers to common questions\n• Plan your outfit (neat, clean, professional)\n• Arrive 10-15 minutes early\n• Bring a copy of your resume\n\n**Common Questions & How to Answer**\n\n*"Tell me about yourself"* — Give a 60-second highlight reel: who you are, what you do, why you're here\n\n*"What are your strengths?"* — Pick 2-3 with real examples\n\n*"What's your weakness?"* — Be honest but show growth: "I used to struggle with time management, so I started using a planner and now I..."  \n\n*"Why do you want this?"* — Show genuine enthusiasm and research\n\n**Body Language**\n✨ Firm handshake\n✨ Eye contact (not staring — natural!)\n✨ Sit up straight, no slouching\n✨ Smile genuinely\n✨ Nod to show you're listening\n\n**After the Interview**\nSend a thank-you email within 24 hours. This sets you apart from most candidates.` },

  // Safety
  { id: 11, cat: 'safety', emoji: '🛡️', title: 'Personal Safety', desc: 'Know your rights, trust your instincts, and always protect yourself.', content: `**Your Safety is Non-Negotiable**\nTrusting your gut has saved countless lives. If something feels wrong, it probably is.\n\n**Street Safety**\n• Stay aware — headphones in both ears = reduced awareness\n• Walk confidently — eyes up, shoulders back\n• Stick to well-lit, populated areas at night\n• Share your location with someone you trust\n• Have emergency contacts on speed dial\n\n**Digital Safety**\n• Never share your home address, school, or daily schedule with strangers online\n• Be cautious of anyone who moves too fast emotionally online\n• Reverse image search profile photos to check for catfishing\n• Anything you send can be screenshot and shared forever\n\n**Relationship Safety**\nRed flags to never ignore:\n🚩 Someone who isolates you from friends/family\n🚩 Controlling or jealous behavior\n🚩 Pressure to do things you're not comfortable with\n🚩 Making you feel bad about yourself\n\n**If You're in Danger**\n• Call 911\n• Text 911 (available in most areas)\n• Tell a trusted adult immediately\n• National DV Hotline: 1-800-799-7233\n\n**Remember:** Getting out of a dangerous situation is never overreacting.` },
  { id: 12, cat: 'safety', emoji: '🔒', title: 'Online Safety & Digital Privacy', desc: 'Learn what never to share, how to spot predators, and protect yourself online.', content: `**The Internet Never Forgets**\nAnything you post, send, or share online can live forever — even if you delete it.\n\n**Never Share Online**\n🚫 Your home address or school name\n🚫 Your daily schedule or routine\n🚫 Financial information\n🚫 Passwords (even with friends)\n🚫 Explicit photos or videos — ever\n\n**Spotting Online Predators**\nWarning signs:\n• Moves very quickly to being your "best friend"\n• Asks overly personal questions early on\n• Wants to move to a private platform quickly\n• Offers money, gifts, or modeling opportunities\n• Says things like "you're so mature for your age"\n• Asks you to keep the relationship secret\n\n**Protecting Your Accounts**\n• Use strong, unique passwords\n• Enable 2-factor authentication\n• Keep accounts private\n• Regularly audit who follows you\n• Turn off location sharing on posts\n\n**If Something Goes Wrong**\n• Tell a trusted adult immediately\n• Screenshot evidence before deleting anything\n• Report to the platform\n• Report to NCMEC CyberTipline: cybertipline.org\n• Call 1-800-THE-LOST` },

  // Studying
  { id: 13, cat: 'studying', emoji: '📖', title: 'Study Skills & Academic Success', desc: 'Master the art of studying smarter, not harder.', content: `**Study Smart, Not Just Hard**\nHours spent staring at a book ≠ actually learning. Here's how to actually retain information.\n\n**The Most Effective Study Methods**\n\n**Active Recall** — Close the book and try to remember what you just read. Quiz yourself.\n\n**Spaced Repetition** — Study a little bit every day instead of cramming the night before. Your brain retains information better this way.\n\n**The Pomodoro Method** — 25 minutes of focused studying, 5-minute break. Repeat 4 times, then take a longer break.\n\n**Teach It** — Explain what you learned to someone else (or even your pet!). If you can teach it, you know it.\n\n**Setting Up to Study**\n• Clean, organized space\n• Phone in another room or on Do Not Disturb\n• Water and a light snack nearby\n• Use lo-fi music or white noise if silence is too distracting\n\n**Before a Test**\n• Review 3 days before, not the night before\n• Get 8+ hours of sleep the night before\n• Eat a real breakfast\n• Arrive early and breathe\n\n💡 Your GPA doesn't define you, but good study habits will serve you for life.` },
  { id: 14, cat: 'studying', emoji: '✏️', title: 'Note-Taking Strategies That Actually Work', desc: 'Transform your notes from messy scribbles into powerful study tools.', content: `**Your Notes Are a Study Tool — Make Them Work**\nBad notes = studying the same material twice. Good notes = studying half as long.\n\n**The Cornell Method**\nDivide your page into 3 sections:\n• **Right column (70%)** — Main notes during class\n• **Left column (30%)** — Key questions and cues after class\n• **Bottom section** — Summary in your own words\n\n**The Outline Method**\nGreat for organized content:\n- Main topic\n  - Subtopic\n    - Detail\n\n**The Mind Map Method**\nPerfect for visual learners. Put the main concept in the center, branch out to subtopics.\n\n**Tips for Better Notes**\n✨ Use abbreviations and symbols\n✨ Write in your own words — don't copy word for word\n✨ Use color coding by topic\n✨ Leave white space — your brain needs breathing room\n✨ Review and add to notes within 24 hours of class\n\n**Digital vs. Handwritten**\nStudies show handwritten notes lead to better retention — your brain processes it differently when your hand writes it.` },
  { id: 15, cat: 'studying', emoji: '🎯', title: 'Test Prep & Exam Strategy', desc: 'Walk into every exam confident, prepared, and ready to show what you know.', content: `**Preparation Is the Confidence Builder**\nYou don't need luck when you've prepared.\n\n**2 Weeks Before**\n• Identify every topic on the test\n• Make a study schedule\n• Gather all notes and materials\n• Form a study group (optional but helpful)\n\n**1 Week Before**\n• Active recall sessions daily\n• Practice tests and past exams\n• Flashcards for memorization\n• Teach concepts to a friend\n\n**Night Before**\n• Light review only — no cramming\n• Prepare your bag and outfit\n• Get 8-9 hours of sleep (this is non-negotiable)\n• No screens for 1 hour before bed\n\n**Day of the Test**\n• Eat a protein-rich breakfast\n• Arrive early and take deep breaths\n• Read every question carefully before answering\n• Skip hard questions and come back\n• Trust your first instinct on multiple choice\n\n**Managing Test Anxiety**\n• 4-7-8 breathing before you start\n• Remind yourself: "I have prepared for this"\n• If you blank, move on and come back` },

  // Black Hair Care
  { id: 16, cat: 'black_hair', emoji: '👑', title: 'Natural Hair Care Basics', desc: 'Love and care for your natural hair with knowledge and tools to keep it healthy.', content: `**Your Crown is Everything**\nNatural hair is beautiful, powerful, and worth every moment of care you give it.\n\n**The Basics of Natural Hair Care**\n\n**Moisture is Everything**\nBlack hair tends to be naturally dry because the natural oils from your scalp have a harder time traveling down the curl. Moisture = life.\n\n**The LOC/LCO Method**\n• **L** — Liquid (water or water-based leave-in)\n• **O** — Oil (seals in moisture — coconut, castor, jojoba)\n• **C** — Cream (thick moisturizer)\nApply in this order for maximum moisture retention.\n\n**Wash Day Basics**\n1. Pre-poo (optional) — oil treatment before washing\n2. Shampoo — focus on scalp, not ends\n3. Deep condition — always! (15-30 min with heat)\n4. Leave-in conditioner\n5. Style while hair is still damp\n\n**Protective Styles**\nBraids, twists, wigs, and weaves protect your ends from breakage. But keep them clean and don't leave them in too long!\n\n**Ingredients to Love**\n✅ Shea butter, castor oil, aloe vera, glycerin\n\n**Ingredients to Avoid**\n🚫 Sulfates (drying), mineral oil (clogs pores), alcohol (drying)` },
  { id: 17, cat: 'black_hair', emoji: '💧', title: 'Understanding Hair Porosity', desc: 'Knowing your hair\'s porosity is the key to choosing products that actually work.', content: `**What is Hair Porosity?**\nPorosity is your hair's ability to absorb and retain moisture. It's determined by your hair cuticle.\n\n**Test Your Porosity**\nDrop a clean strand of hair in a glass of water:\n• Floats → **Low porosity**\n• Sinks slowly → **Medium/Normal porosity**  \n• Sinks fast → **High porosity**\n\n**Low Porosity Hair**\n• Cuticles are tightly closed\n• Water beads up, products sit on top\n• Takes forever to dry\n\n**What Works:** Lightweight products, heat when deep conditioning, clarifying shampoo to remove buildup\n\n**High Porosity Hair**\n• Cuticles have gaps (from heat, chemicals, or genetics)\n• Absorbs moisture quickly but loses it fast\n• Frizzy, prone to breakage\n\n**What Works:** Protein treatments, heavier butters and creams, sealing with oil after moisturizing, cold water rinses\n\n**Normal/Medium Porosity Hair**\n• Most balanced — hold moisture well\n• Responds well to most products\n\n💡 Once you know your porosity, you stop wasting money on products that don't work for you.` },
  { id: 18, cat: 'black_hair', emoji: '✨', title: 'Protective Styles Guide', desc: 'Protective styles for length retention, low manipulation, and giving your hair a break.', content: `**Why Protective Styles Work**\nYour ends are the oldest, most fragile part of your hair. Protecting them = retaining length.\n\n**Popular Protective Styles**\n\n**Braids** (box braids, cornrows, knotless braids)\n• Great for 4-8 weeks\n• Keep moisturizing your scalp weekly\n• Don't braid too tight — it causes breakage and traction alopecia\n\n**Twists** (mini twists, Senegalese twists)\n• Less tension than braids\n• Great for 2-6 weeks\n\n**Wigs & Weaves**\n• Protect your natural hair underneath\n• Keep your natural hair moisturized and clean underneath\n• Give your edges a break — don't glue near your hairline\n\n**Locs**\n• A long-term protective style and lifestyle\n• Require regular retwisting and moisturizing\n\n**Protective Style Care Tips**\n✅ Moisturize your scalp weekly (not just the style)\n✅ Sleep with a satin bonnet or pillowcase always\n✅ Take down before 8 weeks to prevent matting\n✅ Deep condition after taking a style down\n\n⚠️ Never let a stylist braid too tight. Pain = damage.` },

  // Mental Wellness
  { id: 19, cat: 'mental_wellness', emoji: '🙋‍♀️', title: 'People Pleasing: Are You Doing Too Much?', desc: 'Do you say yes when you mean no? Let\'s talk about it.', content: `**Signs You Might Be a People Pleaser**\n• You say yes when you desperately want to say no\n• You change your opinion based on who you're with\n• You feel responsible for other people's emotions\n• You apologize constantly, even when it's not your fault\n• You feel guilty when you prioritize yourself\n• You fear that saying no will make people not like you\n\n**Why We People Please**\nMost people pleasers grew up in environments where their approval was tied to their behavior. Or they were hurt by conflict and learned that keeping the peace = staying safe.\n\n**The Cost of People Pleasing**\n• Resentment builds over time\n• You attract people who take advantage\n• You lose touch with your own wants and needs\n• Anxiety and burnout\n\n**How to Stop**\n1. **Pause before responding** — "Let me think about that and get back to you"\n2. **Practice saying no** — Start small. "I can't make it tonight."\n3. **Recognize your needs matter too** — Your comfort is not less important than others'\n4. **Notice the guilt** — Feeling guilty for saying no doesn't mean you did something wrong\n\n💡 Saying no to what doesn't serve you is saying yes to yourself.` },
  { id: 20, cat: 'mental_wellness', emoji: '🧘‍♀️', title: 'Mental Wellness & Self-Care', desc: 'Your mental health matters just as much as your physical health.', content: `**Mental Health is Health**\nYou wouldn't ignore a broken arm. Don't ignore a struggling mind.\n\n**Signs Your Mental Health Needs Attention**\n• Persistent sadness or emptiness\n• Losing interest in things you used to love\n• Changes in sleep (too much or too little)\n• Withdrawing from friends and family\n• Feeling hopeless about the future\n• Irritability or anger that feels out of control\n\n**Daily Mental Health Habits**\n• Sleep 8-9 hours (this is the #1 mental health tool)\n• Move your body — even a 20-minute walk helps\n• Limit social media (2 hours/day max)\n• Talk to someone you trust\n• Journal — get your thoughts out of your head\n• Do one thing you enjoy every day\n\n**When to Get Help**\nTalk to a school counselor, trusted adult, or therapist if:\n• Symptoms persist for 2+ weeks\n• You're having thoughts of hurting yourself\n• Daily functioning is affected\n\n**Crisis Resources**\n📱 Crisis Text Line: Text HOME to 741741\n📞 988 Suicide & Crisis Lifeline: Call or text 988\n\n💡 Asking for help is not weakness — it's the strongest thing you can do.` },
  { id: 21, cat: 'mental_wellness', emoji: '🌿', title: 'Staying Present in the Moment', desc: 'How to stop living in your worries and actually experience your life.', content: `**The Problem with Living in Your Head**\nWhen your mind is always in the past (ruminating) or the future (worrying), you miss the only thing that's real — right now.\n\n**What is Mindfulness?**\nMindfulness just means paying attention to the present moment on purpose, without judgment.\n\n**Simple Ways to Be More Present**\n\n**5-4-3-2-1 Technique:**\n• 5 things you can see\n• 4 things you can touch\n• 3 things you can hear\n• 2 things you can smell\n• 1 thing you can taste\n\n**Mindful Eating:** Put the phone down. Taste your food. Notice textures and flavors.\n\n**Mindful Walking:** Feel your feet on the ground. Notice the air. Look around.\n\n**Tech Boundaries for Presence**\n• No phone for the first 30 minutes after waking up\n• Phone-free meals\n• One social media check per day\n• No phone in bed\n\n💡 The most important moment of your life is always this one.` },

  // Growth Mindset
  { id: 22, cat: 'growth_mindset', emoji: '🧠', title: 'Growth Mindset vs Fixed Mindset', desc: 'Your mindset is the story you tell yourself about who you are.', content: `**What is a Mindset?**\nA mindset is the set of beliefs you hold about yourself and your abilities.\n\n**Fixed Mindset Says:**\n• "I'm just not smart."\n• "I can't do math — I never could."\n• "She's naturally talented. I'll never be that good."\n• "I failed, so I must not be cut out for this."\n\n**Growth Mindset Says:**\n• "I'm not good at this *yet*."\n• "What can I learn from this failure?"\n• "She worked hard to get there. I can too."\n• "This is difficult, which means I'm growing."\n\n**The Science**\nResearcher Carol Dweck at Stanford proved that believing you can improve actually changes what's possible for you. Your brain physically grows new connections when you learn.\n\n**Shifting Your Mindset**\nWhenever you hear a fixed mindset thought:\n1. Notice it — "There's that fixed mindset voice."\n2. Acknowledge it — "I understand you're trying to protect me."\n3. Redirect it — "But what if I try anyway?"\n\n**The Power of YET**\nAdd the word "yet" to your fixed thoughts:\n"I don't understand this" → "I don't understand this *yet*"` },

  // Real Life Skills
  { id: 23, cat: 'real_life', emoji: '🚗', title: 'Buying Your First Car', desc: 'Everything you need to know about buying a car — don\'t let a dealership play you.', content: `**Knowledge is Protection at a Dealership**\nDealerships are in the business of making money. Go in informed.\n\n**Step 1: Set Your Budget**\n• Car payment should be no more than 15% of your monthly income\n• Don't forget: insurance, gas, maintenance, registration\n\n**Step 2: New vs. Used**\nFor a first car, used (1-4 years old, low mileage) is almost always the smarter choice. New cars lose 20% of their value the moment you drive off the lot.\n\n**Step 3: Research Before You Go**\n• Use Carfax or AutoCheck to check vehicle history\n• Get a pre-purchase inspection from an independent mechanic\n• Look up fair market value on Kelley Blue Book (KBB)\n\n**Step 4: At the Dealership**\n• Get pre-approved for financing before going (your bank or credit union)\n• Negotiate the price, not the monthly payment\n• Never sign the same day — sleep on it\n• Read every line before signing\n\n**Red Flags**\n🚩 Pressure to sign today\n🚩 "Special deal only good right now"\n🚩 Fees you weren't told about beforehand` },
  { id: 24, cat: 'real_life', emoji: '🏡', title: 'Buying a Home', desc: 'Homeownership is one of the biggest wealth-building tools available.', content: `**Why Homeownership Matters**\nWhen you pay rent, you're building someone else's wealth. When you own, you build equity — money that belongs to you.\n\n**Start Preparing Now**\nEven if you're years away, these habits matter:\n• **Build credit** — Get a secured credit card, pay it off monthly\n• **Save for a down payment** — Aim for 3-20% of the home price\n• **Reduce debt** — Student loans, car payments affect what you qualify for\n\n**How a Mortgage Works**\nA bank lends you money to buy a home. You pay it back monthly (principal + interest) over 15-30 years. As you pay, you build equity.\n\n**The Home Buying Process**\n1. Get pre-approved for a mortgage\n2. Find a real estate agent\n3. Search for homes in your budget\n4. Make an offer\n5. Inspection and appraisal\n6. Close the deal and get your keys!\n\n**First-Time Buyer Programs**\n• FHA loans (3.5% down payment)\n• Down payment assistance programs (many cities/states offer these)\n• First-time homebuyer tax credits\n\n💡 The best time to start preparing for homeownership is always right now.` },
  { id: 25, cat: 'real_life', emoji: '🚪', title: 'How to Leave an Uncomfortable Situation', desc: 'Real scripts and exit plans for getting yourself out of situations that don\'t feel right.', content: `**Your Discomfort is a Signal — Honor It**\nYou never need a reason to leave a situation that doesn't feel right. Your safety and comfort are enough reason.\n\n**Exit Scripts That Work**\n\n"I have to go — my mom/dad just texted me."\n"I'm not feeling well, I need to head out."\n"I just remembered I have somewhere to be."\n"This isn't really my scene — I'm gonna head out."\n"I need some air — I'll catch you later."\n\n**The Fake Call Trick**\nSet a timer on your phone for 15-20 minutes after arriving somewhere you're unsure about. When it goes off, take the "call" and excuse yourself.\n\n**If You Feel Unsafe**\n• Get to a public, well-lit area\n• Call 911 if you feel in immediate danger\n• Text a friend your location\n• Use the Companion app — it lets someone virtually walk you home\n\n**Driving Safety**\nIf the driver is intoxicated or driving dangerously:\n• Ask them to pull over\n• Call someone to pick you up — there is always a way home\n• You can always call 911\n• No ride is worth your life\n\n💡 A real friend will never be upset that you left a situation to keep yourself safe.` },

  // Road Rules
  { id: 26, cat: 'road_rules', emoji: '🚨', title: 'How to Handle Getting Pulled Over', desc: 'Knowing exactly what to do keeps you safe, calm, and legally protected.', content: `**Stay Calm — You Can Handle This**\nGetting pulled over is stressful but manageable. What you do in those moments matters.\n\n**Immediately When You See Lights**\n1. Turn on your hazard lights\n2. Slow down gradually and pull to the right side of the road\n3. Put the car in park and turn off the engine\n4. Turn on interior lights if it's dark\n5. Keep both hands visible on the steering wheel\n\n**When the Officer Approaches**\n• Don't reach for anything until asked\n• Speak calmly and respectfully\n• Say: "Officer, my license and registration are in my [glove box / wallet]. May I reach for them?"\n\n**Know Your Rights**\n• You have the right to remain silent beyond providing your license, registration, and insurance\n• You can decline a vehicle search: "I do not consent to a search"\n• You cannot be detained indefinitely without reason\n• If you feel your rights were violated, address it in court — not on the roadside\n\n**Protect Yourself**\n• Remain calm even if treated unfairly\n• Document badge numbers and officer names after the stop\n• Contact the ACLU or a lawyer if needed\n\n💡 How you handle this moment can affect the outcome significantly.` },
  { id: 27, cat: 'road_rules', emoji: '🛡️', title: 'Car Insurance 101', desc: 'Car insurance isn\'t optional — it\'s the law.', content: `**What is Car Insurance?**\nCar insurance protects you financially if you're in an accident, your car is stolen, or you damage someone else's property.\n\n**Types of Coverage**\n\n**Liability (Required in most states)**\n• Covers damage you cause to others\n• Has two parts: bodily injury + property damage\n\n**Collision**\n• Covers damage to YOUR car in an accident\n• Required if you have a car loan\n\n**Comprehensive**\n• Covers theft, weather damage, hitting an animal\n• "Everything except a collision"\n\n**Uninsured Motorist**\n• Protects you if the other driver has no insurance\n\n**Understanding Your Policy**\n• **Premium** — What you pay monthly\n• **Deductible** — What you pay out-of-pocket before insurance kicks in\n• **Coverage limits** — The max your insurance will pay\n\n**Reducing Your Premium**\n• Good grades discount (many insurers offer this for teens!)\n• Stay on parents' policy if possible\n• Take a defensive driving course\n• Keep a clean driving record\n\n💡 Always carry proof of insurance in your car and on your phone.` },

  // Beauty
  { id: 28, cat: 'beauty', emoji: '💅', title: 'Nails on a Budget', desc: 'Keep your nails looking clean, polished, and cute without spending a lot.', content: `**Clean Nails = Put-Together Look**\nYou don't need a salon visit to have beautiful nails.\n\n**Essential Tools**\n• Nail file and buffer (drugstore — under $5)\n• Nail clippers\n• Base coat (protects nails)\n• A few nail polish colors you love\n• Top coat (makes polish last 2x longer)\n• Cuticle oil or coconut oil\n\n**Simple At-Home Manicure**\n1. Remove old polish completely\n2. Clip and file — always file in one direction\n3. Soak hands in warm water for 5 minutes\n4. Push back cuticles (never cut them)\n5. Apply base coat\n6. Apply 2 thin coats of color (let each dry!)\n7. Apply top coat\n8. Apply cuticle oil\n\n**Budget-Friendly Nail Polish Brands**\n• Sally Hansen (drugstore, great quality)\n• Essie (affordable, wide range)\n• OPI (splurge when on sale)\n• Wet n Wild (very affordable)\n\n**Making It Last**\n• Reapply top coat every 2-3 days\n• Wear gloves when washing dishes\n• Apply cuticle oil daily\n\n💅 Nails are jewelry you always have on — take care of them!` },
  { id: 29, cat: 'beauty', emoji: '💄', title: 'Everyday Makeup on a Budget', desc: 'Look polished and put-together every day without spending a lot.', content: `**The 5-Minute Budget Makeup Routine**\nYou don't need a full face to look polished. A few key products go a long way.\n\n**The Essential 5 Products**\n1. **Tinted moisturizer or BB cream** — Evens skin tone, feels light\n2. **Concealer** — Covers dark circles and blemishes\n3. **Mascara** — Opens up your eyes instantly\n4. **Tinted lip balm or gloss** — Adds a healthy glow\n5. **Brow pencil or gel** — Frames your face\n\n**Budget Drugstore Picks**\n• e.l.f. Cosmetics (everything under $15)\n• Wet n Wild (amazing quality, ultra affordable)\n• NYX Professional Makeup\n• Maybelline Fit Me Concealer/Foundation\n• L'Oreal Telescopic Mascara\n\n**Makeup Tips for Beginners**\n• Less is more — build up gradually\n• Blend everything — harsh lines are the #1 mistake\n• Match foundation to your jaw, not your wrist\n• Remove makeup every single night\n• Clean brushes weekly\n\n**Money-Saving Tips**\n• Buy during Ulta 21 Days of Beauty sales\n• Check dupes on Reddit (r/MakeupAddiction)\n• Multi-use products (lip color as blush, etc.)` },

  // Character & Values
  { id: 30, cat: 'character', emoji: '💡', title: 'The Power of Honesty', desc: 'Why being truthful — with yourself and others — is one of the most powerful things you can do.', content: `**Honesty is a Superpower**\nIn a world full of filters, facades, and fake smiles — being genuinely honest is rare and powerful.\n\n**Honesty With Others**\nHonest people:\n• Are trusted more in relationships and professionally\n• Attract real, authentic friendships\n• Sleep better at night (no stories to keep straight)\n• Are taken more seriously\n• Build reputations that last\n\n**Honesty With Yourself**\nThis is the hardest kind. Self-honesty means:\n• Admitting when you're wrong\n• Acknowledging your flaws without shame\n• Recognizing when a relationship or situation isn't working\n• Owning your part in conflicts\n• Being honest about what you actually want\n\n**When It's Hard to Be Honest**\nSometimes being honest means:\n• Having a difficult conversation\n• Disappointing someone\n• Admitting you need help\n• Saying "I was wrong"\n\nNone of these are comfortable — but all of them build character.\n\n**Honesty vs. Harshness**\nHonesty doesn't mean being brutal. The goal is truth delivered with kindness.\n\n💡 "The truth will set you free, but first it will make you uncomfortable."` },

  // Life Skills
  { id: 31, cat: 'life_skills', emoji: '🏛️', title: 'Sororities & Greek Life', desc: 'Everything about joining a sorority — the culture, sisterhood, and how to prepare.', content: `**What is Greek Life?**\nSororities are women's organizations at colleges and universities that focus on sisterhood, service, leadership, and academics.\n\n**Types of Sororities**\n\n**National Panhellenic Conference (NPC)**\nTraditionally white-founded sororities. Focus on recruitment during formal "rush" periods.\nExamples: Alpha Chi Omega, Kappa Delta, Zeta Tau Alpha\n\n**National Pan-Hellenic Council (NPHC) — The "Divine Nine"**\nHistorically Black sororities and fraternities.\nExamples: Alpha Kappa Alpha (ΑΚΑ), Delta Sigma Theta (ΔΣΘ), Sigma Gamma Rho, Zeta Phi Beta\n\n**How to Prepare**\n• Maintain a strong GPA (most chapters require 2.5-3.0+)\n• Get involved on campus and in community service\n• Build genuine relationships\n• Learn about each organization's values and history\n\n**Things to Know**\n• Dues can range from hundreds to thousands per semester\n• Some chapters "haze" — know the signs and know your rights\n• Real sisterhood is built on mutual respect, not hazing\n• Greek life is what you make it — go in with intention\n\n💡 Research each organization's national values and legacy before committing.` },
  { id: 32, cat: 'life_skills', emoji: '🚗', title: 'Car Maintenance Every Girl Should Know', desc: 'Learn the basics that keep you safe, save you money, and make you independent.', content: `**Car Basics Every Driver Should Know**\nYou shouldn't need to rely on someone else for basic car knowledge.\n\n**Check These Monthly**\n\n**Oil Level**\nPull the dipstick, wipe it, reinsert, pull again. Oil should be between the two marks and golden/brown (not black).\n\n**Tire Pressure**\nCheck when tires are cold. Use a pressure gauge. Correct PSI is on the door jamb sticker.\n\n**Windshield Wiper Fluid**\nNever let this run out — especially in winter.\n\n**When to Schedule Service**\n• **Oil change** — Every 3,000-5,000 miles (conventional) or 7,500-10,000 (synthetic)\n• **Tire rotation** — Every 5,000-7,500 miles\n• **Tire replacement** — When tread depth is at 2/32"\n• **Brake check** — If you hear squealing or grinding\n\n**Emergency Kit in Your Car**\n🔦 Flashlight\n🔋 Jumper cables\n🪛 Basic toolkit\n🧯 Fire extinguisher\n🏕️ Emergency blanket\n📋 Insurance and registration copies\n\n**When Your Car Warning Lights Come On**\n• Check Engine — Get diagnosed soon\n• Oil light — Stop driving, check oil immediately\n• Temperature — Pull over, let engine cool` },

  // Healthy Eating
  { id: 33, cat: 'healthy_eating', emoji: '🥗', title: 'Healthy Eating for Teen Girls', desc: 'Fuel your body right for energy, glowing skin, and mental clarity.', content: `**Food is Fuel — And So Much More**\nWhat you eat affects your energy, skin, mood, focus, and how you feel about yourself.\n\n**What Your Body Needs**\n• **Protein** — Builds muscle, keeps you full: eggs, chicken, beans, Greek yogurt, nuts\n• **Complex Carbs** — Sustained energy: oats, brown rice, sweet potatoes, whole grain bread\n• **Healthy Fats** — Brain food and hormone health: avocado, olive oil, nuts, salmon\n• **Fiber** — Gut health and fullness: fruits, vegetables, beans\n• **Iron** — Especially important for girls (periods deplete iron): red meat, spinach, fortified cereals\n• **Calcium** — Bone strength: dairy, fortified plant milks, leafy greens\n\n**Building a Balanced Plate**\n• Half your plate: vegetables and fruits\n• Quarter: protein\n• Quarter: whole grains\n• Plus healthy fats\n\n**Eating on a Budget**\n• Buy frozen vegetables (just as nutritious as fresh)\n• Eggs are cheap and incredibly nutritious\n• Oats, beans, and rice are budget superfoods\n• Buy in season\n\n**Hydration**\nDrink 8-10 glasses of water daily. Dehydration causes fatigue, headaches, and poor concentration.\n\n💡 Healthy eating isn't about being perfect — it's about nourishing yourself consistently.` },

  // Time Management
  { id: 34, cat: 'time_mgmt', emoji: '⏰', title: 'Time Management for Teen Girls', desc: 'Own your schedule before it owns you.', content: `**Time is Your Most Valuable Resource**\nYou can always make more money. You cannot make more time.\n\n**Why Time Management Matters**\nGirls who manage their time well:\n• Stress less (they know what's coming)\n• Sleep more (no all-nighters)\n• Do better academically\n• Have more free time (not less!)\n• Feel more in control of their lives\n\n**Time Management Tools**\n\n**Time Blocking**\nAssign specific activities to specific time blocks in your day. Example: 4-5pm = homework, 5-6pm = workout, 7-8pm = free time.\n\n**The Eisenhower Matrix**\nSort tasks by urgency and importance:\n• Urgent + Important → Do it now\n• Important but Not Urgent → Schedule it\n• Urgent but Not Important → Delegate\n• Neither → Delete it\n\n**Weekly Planning**\nEvery Sunday, spend 15 minutes:\n• Writing out the week's commitments\n• Identifying priority tasks\n• Scheduling self-care and rest\n\n**Fighting Procrastination**\n• The 2-minute rule: if it takes less than 2 minutes, do it now\n• Start with the hardest task first\n• Break big projects into small daily steps\n\n💡 You'll never find time — you have to make it.` },
];

export default function GirlsLibrary() {
  const navigate = useNavigate();
  const [activeSection, setActiveSection] = useState('resources');
  const [activeCategory, setActiveCategory] = useState('all');
  const [selectedResource, setSelectedResource] = useState(null);

  const filtered = RESOURCES.filter(r => {
    return activeCategory === 'all' || r.cat === activeCategory;
  });

  const renderContent = (text) => {
    return text.split('\n').map((line, i) => {
      if (line.startsWith('**') && line.endsWith('**')) {
        return <p key={i} className="font-bold text-white mt-3 mb-1">{line.replace(/\*\*/g, '')}</p>;
      }
      if (line.match(/^\*\*.+\*\*/)) {
        return <p key={i} className="text-sm text-gray-200 mb-1" dangerouslySetInnerHTML={{ __html: line.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>') }} />;
      }
      if (line.startsWith('• ') || line.startsWith('✅ ') || line.startsWith('🚫 ') || line.startsWith('🚩 ') || line.startsWith('✨ ') || line.startsWith('💡 ')) {
        return <p key={i} className="text-sm text-gray-300 mb-1 pl-2">{line}</p>;
      }
      if (line.trim() === '') return <div key={i} className="h-1" />;
      return <p key={i} className="text-sm text-gray-300 mb-1">{line}</p>;
    });
  };

  return (
    <div className="min-h-screen text-white pb-24 relative" style={{ backgroundColor: '#0d0010' }}>
      <AppBackground />

      <div className="relative z-10">
        {/* Header */}
        <div className="px-4 pt-4 pb-2">
          <div className="flex items-center gap-2 mb-3">
            <button onClick={() => navigate(-1)} className="text-gray-400"><ChevronLeft size={22} /></button>
            <div className="flex items-center gap-2">
              <BookOpen size={14} className="text-gray-400" />
              <span className="text-xs font-bold tracking-widest text-gray-400">GIRLS LIBRARY</span>
            </div>
          </div>
          <h1 className="text-3xl font-bold text-white mb-1">Girls Library 📚</h1>
          <p className="text-sm text-gray-400 mb-4">Knowledge, guides, and curated books to help you thrive.</p>

          {/* Recommended banner */}
          <div className="rounded-2xl px-4 py-3 mb-4"
            style={{ background: 'linear-gradient(135deg, rgba(109,40,217,0.5), rgba(139,10,120,0.4))', border: '1px solid rgba(168,85,247,0.3)' }}>
            <p className="text-xs font-bold text-yellow-300 mb-0.5">✨ Recommended For You</p>
            <p className="text-xs text-gray-300">Resources handpicked based on your interests and growth stage</p>
          </div>
        </div>

        {/* Section Tabs */}
        <div className="flex gap-2 overflow-x-auto px-4 pb-2 scrollbar-none">
          {SECTION_TABS.map(tab => (
            <button key={tab.id} onClick={() => setActiveSection(tab.id)}
              className={`flex-shrink-0 flex items-center gap-1.5 px-4 py-2 rounded-full text-sm font-medium transition whitespace-nowrap`}
              style={activeSection === tab.id
                ? { background: 'rgba(255,255,255,0.15)', border: '1px solid rgba(255,255,255,0.3)', color: '#fff' }
                : { background: 'transparent', border: '1px solid rgba(255,255,255,0.1)', color: '#9ca3af' }}>
              {tab.emoji && <span>{tab.emoji}</span>}
              {tab.label}
            </button>
          ))}
        </div>

        {/* Category Filter Chips */}
        <div className="flex gap-2 overflow-x-auto px-4 pt-3 pb-3 scrollbar-none">
          {CATEGORIES.map(cat => (
            <button key={cat.id} onClick={() => setActiveCategory(cat.id)}
              className={`flex-shrink-0 flex items-center gap-1 px-3 py-1.5 rounded-full text-xs font-semibold transition whitespace-nowrap`}
              style={activeCategory === cat.id
                ? { background: 'rgba(255,255,255,0.2)', border: '1px solid rgba(255,255,255,0.4)', color: '#fff' }
                : { background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', color: '#9ca3af' }}>
              {cat.emoji && <span>{cat.emoji}</span>}
              {cat.label}
            </button>
          ))}
        </div>

        {/* 2-Column Grid */}
        <div className="grid grid-cols-2 gap-3 px-4 pt-1">
          {filtered.map(r => (
            <button key={r.id} onClick={() => setSelectedResource(r)}
              className="flex flex-col items-center justify-center gap-3 rounded-2xl py-8 px-4 text-center transition hover:opacity-80"
              style={{ background: 'rgba(60,20,80,0.7)', border: '1px solid rgba(255,255,255,0.07)', minHeight: 140 }}>
              <span className="text-4xl">{r.emoji}</span>
              <p className="text-xs font-semibold text-gray-200 leading-tight">{CATEGORIES.find(c => c.id === r.cat)?.label || r.cat}</p>
            </button>
          ))}

          {filtered.length === 0 && (
            <div className="col-span-2 text-center py-10">
              <p className="text-4xl mb-3">📚</p>
              <p className="text-white font-semibold">No resources here yet</p>
              <p className="text-gray-500 text-sm mt-1">Try a different category</p>
            </div>
          )}
        </div>
      </div>

      {/* Resource Detail Modal */}
      {selectedResource && (
        <div className="fixed inset-0 z-50 flex flex-col" style={{ backgroundColor: '#0d0010' }}>
          <div className="flex items-center gap-2 px-4 pt-4 pb-3 flex-shrink-0"
            style={{ borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
            <button onClick={() => setSelectedResource(null)} className="text-gray-400">
              <ChevronLeft size={22} />
            </button>
            <div className="flex-1">
              <p className="text-xs text-pink-400 font-semibold">{CATEGORIES.find(c => c.id === selectedResource.cat)?.emoji} {CATEGORIES.find(c => c.id === selectedResource.cat)?.label}</p>
            </div>
          </div>
          <div className="flex-1 overflow-y-auto px-4 pt-4 pb-24">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-14 h-14 rounded-2xl flex items-center justify-center text-3xl flex-shrink-0"
                style={{ background: 'rgba(236,72,153,0.15)', border: '1px solid rgba(236,72,153,0.2)' }}>
                {selectedResource.emoji}
              </div>
              <div>
                <h1 className="text-xl font-bold text-white">{selectedResource.title}</h1>
                <p className="text-xs text-gray-400 mt-0.5">{selectedResource.desc}</p>
              </div>
            </div>
            <div className="rounded-2xl p-4" style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)' }}>
              {renderContent(selectedResource.content)}
            </div>
            <LibraryQuiz key={selectedResource.id} quiz={QUIZZES[selectedResource.id]} />
          </div>
        </div>
      )}

      <BottomNav active="discover" />
    </div>
  );
}