export const CATEGORIES = [
  'All', 'Business', 'Healthcare', 'Law', 'Technology', 'Education',
  'Mental Health', 'Creative Arts', 'Finance', 'Media', 'Science', 'Design',
  'Beauty & Wellness', 'Tech & Digital', 'Creative & Media',
  'Education & Social Impact', 'Law & Justice', 'Trades & Entrepreneurship',
];

export const EXPERIENCE_LEVELS = ['All Levels', 'Entry Level', 'Mid Level', 'Senior Level', 'Executive'];

export const CATEGORY_COLORS = {
  Business: '#a855f7', Healthcare: '#06b6d4', Law: '#f59e0b', Technology: '#22c55e',
  Education: '#f97316', 'Mental Health': '#ec4899', 'Creative Arts': '#ef4444',
  Finance: '#10b981', Media: '#8b5cf6', Science: '#14b8a6', Design: '#6366f1',
  'Beauty & Wellness': '#f472b6', 'Tech & Digital': '#3b82f6', 'Creative & Media': '#e879f9',
  'Education & Social Impact': '#fb923c', 'Law & Justice': '#fbbf24',
  'Trades & Entrepreneurship': '#84cc16',
};

export const EXP_COLORS = {
  'Entry Level': '#22c55e',
  'Mid Level': '#3b82f6',
  'Senior Level': '#f59e0b',
  'Executive': '#ec4899',
};

const DEFAULT_DATA = {
  Business: {
    glow_quote: "You create your own rules, your own schedule, and your own legacy.",
    day_in_life: ['Morning team check-in', 'Review sales and analytics', 'Meet with clients or partners', 'Work on marketing strategy', 'Plan next product launch'],
    skills: ['Leadership', 'Communication', 'Problem-solving', 'Financial literacy', 'Marketing'],
    side_hustles: ['Sell handmade products', 'Offer tutoring or coaching', 'Start a YouTube channel', 'Flip items online'],
    real_woman: { name: 'Jasmine', emoji: '👩🏾‍💼', title: 'Tech CEO & Founder', school: 'Howard University (Computer Science)', quote: "You don't need permission to build something that changes the world.", badge: 'Real Woman' },
    education_path: ['Business, Marketing, or Finance degree (optional)', 'Online courses in entrepreneurship', 'Start a small business NOW — age is no barrier'],
    career_ladder: [
      { title: 'Startup Founder', years: '0–2 years', salary: '$0–$30K', desc: 'Building your first product or service, learning everything.' },
      { title: 'Small Business Owner', years: '2–5 years', salary: '$30K–$100K', desc: 'Profitable business with a small team. Scaling up.' },
      { title: 'Established CEO', years: '5–10 years', salary: '$100K–$500K+', desc: 'Multiple employees, brand recognition, and real revenue.' },
      { title: 'Empire Builder', years: '10+ years', salary: '$500K–$1M+', desc: 'Multiple businesses, investments, and generational wealth.' },
    ],
    licensing: ['Business license (varies by state)', 'LLC or S-Corp registration'],
    start_now: {
      classes: ['Business Math', 'Economics', 'Marketing', 'Computer Science'],
      clubs: ['DECA', 'FBLA (Future Business Leaders of America)', 'Junior Achievement'],
      experience: ['Start a small business (Etsy, lawn care, tutoring)', 'Attend local business networking events'],
      certifications: ['Google Digital Marketing Certificate', 'HubSpot Marketing Certificate'],
      competitions: ['DECA competitions', 'Pitch competitions', 'Young Entrepreneurs competitions'],
    },
  },
  Healthcare: {
    glow_quote: "Healing people is the most powerful thing you can do with your life.",
    day_in_life: ['Morning patient rounds', 'Review lab results and charts', 'Consultations with patients', 'Coordinate with care team', 'Document patient progress'],
    skills: ['Empathy', 'Attention to detail', 'Science knowledge', 'Critical thinking', 'Stamina'],
    side_hustles: ['Health coaching', 'CPR certification training', 'Medical writing', 'Telehealth consulting'],
    real_woman: { name: 'Dr. Kizzmekia', emoji: '🔬', title: 'Vaccine Scientist', school: 'UNC Chapel Hill (Biology)', quote: "Science is for everyone — especially girls who were told otherwise.", badge: 'Real Woman' },
    education_path: ['Excel in biology, chemistry, and math in high school', 'Get a pre-med or nursing degree', 'Complete clinical hours, residency, or certification program'],
    career_ladder: [
      { title: 'Medical Assistant / CNA', years: '0–2 years', salary: '$30K–$50K', desc: 'Entry point into hands-on patient care.' },
      { title: 'Registered Nurse / Tech', years: '2–5 years', salary: '$60K–$90K', desc: 'Direct patient care and clinical expertise.' },
      { title: 'Nurse Practitioner / PA', years: '5–8 years', salary: '$90K–$130K', desc: 'Advanced practice with more autonomy.' },
      { title: 'Physician / Specialist', years: '10+ years', salary: '$200K–$400K+', desc: 'Top of the field, leading your specialty.' },
    ],
    licensing: ['State medical/nursing license', 'Board certification in specialty', 'BLS/ACLS certification'],
    start_now: {
      classes: ['Biology', 'Chemistry', 'AP Sciences', 'Health Sciences'],
      clubs: ['HOSA (Health Occupations Students of America)', 'Science Club', 'Red Cross Club'],
      experience: ['Volunteer at a hospital or clinic', 'Shadow a healthcare professional'],
      certifications: ['CPR/First Aid', 'CNA Certification', 'EMT Basic'],
      competitions: ['HOSA competitions', 'Science Olympiad', 'Biology Olympiad'],
    },
  },
  Law: {
    glow_quote: "Your voice is your greatest weapon. Use it to fight for those who cannot.",
    day_in_life: ['Review case files and evidence', 'Legal research and writing', 'Client meetings', 'Court appearances or depositions', 'Draft contracts or briefs'],
    skills: ['Analytical reasoning', 'Writing', 'Public speaking', 'Research', 'Persuasion'],
    side_hustles: ['Legal document prep', 'Paralegal freelance work', 'Law tutoring', 'Legal blogging'],
    real_woman: { name: 'Ketanji', emoji: '⚖️', title: 'Supreme Court Justice', school: 'Harvard Law School', quote: "Be the change you want to see in every courtroom.", badge: 'Real Woman' },
    education_path: ['Build strong reading and writing skills', 'Get a 4-year degree (any major)', 'Take the LSAT and apply to law school', 'Pass the bar exam'],
    career_ladder: [
      { title: 'Paralegal / Law Clerk', years: '0–2 years', salary: '$40K–$65K', desc: 'Supporting attorneys with research and documents.' },
      { title: 'Associate Attorney', years: '3–5 years', salary: '$70K–$150K', desc: 'Practicing law at a firm or organization.' },
      { title: 'Senior Attorney / Partner', years: '6–10 years', salary: '$150K–$300K+', desc: 'Leading cases and mentoring junior lawyers.' },
      { title: 'Judge / General Counsel', years: '10+ years', salary: '$150K–$250K+', desc: 'Top of the legal profession.' },
    ],
    licensing: ['Juris Doctor (JD) degree', 'State bar exam passage', 'Background check clearance'],
    start_now: {
      classes: ['English/Debate', 'AP Government', 'History', 'Philosophy'],
      clubs: ['Mock Trial', 'Debate Team', 'Model UN'],
      experience: ['Intern at a law firm', 'Volunteer at legal aid clinics'],
      certifications: ['LSAT prep courses', 'Legal research tools (Westlaw, LexisNexis)'],
      competitions: ['Mock Trial tournaments', 'Moot court competitions', 'Debate championships'],
    },
  },
  Technology: {
    glow_quote: "The future is coded by those brave enough to type the first line.",
    day_in_life: ['Morning standup with the team', 'Write and review code', 'Debug features and fix issues', 'Collaborate with designers', 'Deploy updates to production'],
    skills: ['Coding', 'Problem solving', 'Logic', 'Continuous learning', 'Collaboration'],
    side_hustles: ['Build freelance websites', 'Create an app', 'Sell digital products', 'Teach coding online'],
    real_woman: { name: 'Kimberly', emoji: '💻', title: 'Tech Founder & Engineer', school: 'Vanderbilt University (Engineering)', quote: "Black girls belong in tech — not just as users, but as builders.", badge: 'Real Woman' },
    education_path: ['Learn to code (Python, JavaScript, or Swift)', 'Build small projects and apps', 'Get a CS degree or attend a coding bootcamp', 'Apply for internships at tech companies'],
    career_ladder: [
      { title: 'Junior Developer', years: '0–2 years', salary: '$60K–$90K', desc: 'Learning the codebase and building features.' },
      { title: 'Software Engineer', years: '2–5 years', salary: '$90K–$150K', desc: 'Owning features and systems end-to-end.' },
      { title: 'Senior Engineer / Lead', years: '5–8 years', salary: '$150K–$220K', desc: 'Architecting systems, mentoring the team.' },
      { title: 'Engineering Manager / CTO', years: '8+ years', salary: '$200K–$400K+', desc: 'Leading engineering orgs and technical direction.' },
    ],
    licensing: ['No required license', 'Cloud certifications (AWS, Google Cloud)', 'Security clearances for some roles'],
    start_now: {
      classes: ['Computer Science', 'AP Computer Science', 'Algebra/Statistics', 'Physics'],
      clubs: ['Coding Club', 'Girls Who Code', 'Robotics Team'],
      experience: ['Build a simple website or app', 'Contribute to open-source projects'],
      certifications: ['Google IT Support Certificate', 'AWS Cloud Practitioner', 'Codecademy courses'],
      competitions: ['FIRST Robotics', 'Hackathons', 'Science Olympiad (Tech events)'],
    },
  },
  Education: {
    glow_quote: "The most powerful person in any room is the one who can teach others.",
    day_in_life: ['Prepare lesson plans', 'Teach and engage students', 'Grade assignments and give feedback', 'Parent or admin meetings', 'After-school activities'],
    skills: ['Patience', 'Communication', 'Organization', 'Creativity', 'Empathy'],
    side_hustles: ['Private tutoring', 'Create online courses', 'Educational content creation', 'Curriculum consulting'],
    real_woman: { name: 'Ms. Taylor', emoji: '📚', title: 'Award-Winning Teacher', school: 'Spelman College (Education)', quote: "Every child who walks through my door gets my whole heart.", badge: 'Real Woman' },
    education_path: ['Study hard and develop patience', 'Volunteer or tutor younger students', 'Get a degree in Education', 'Complete student teaching and get certified'],
    career_ladder: [
      { title: 'Student Teacher / Tutor', years: '0–2 years', salary: '$25K–$40K', desc: 'Learning the craft of teaching.' },
      { title: 'Classroom Teacher', years: '2–7 years', salary: '$45K–$75K', desc: 'Full-time educator with your own classroom.' },
      { title: 'Department Head / Coach', years: '7–12 years', salary: '$65K–$90K', desc: 'Leading curriculum and mentoring other teachers.' },
      { title: 'Principal / Director', years: '12+ years', salary: '$85K–$130K+', desc: 'Running a school or district program.' },
    ],
    licensing: ['State teaching certificate', 'Background check clearance', 'Subject area endorsements'],
    start_now: {
      classes: ['English', 'Child Development', 'Psychology', 'Math'],
      clubs: ['Peer Tutoring Program', 'National Honor Society', 'Student Council'],
      experience: ['Tutor younger students', 'Volunteer at summer programs'],
      certifications: ['CPR certification', 'ACT/SAT prep tutor certification'],
      competitions: ['Teacher cadet programs', 'FCCLA competitions'],
    },
  },
  'Mental Health': {
    glow_quote: "You give people permission to heal — and that is one of the most sacred gifts.",
    day_in_life: ['Review client session notes', 'Individual therapy sessions', 'Group therapy facilitation', 'Crisis intervention calls', 'Documentation and reports'],
    skills: ['Active listening', 'Empathy', 'Boundaries', 'Psychology knowledge', 'Patience'],
    side_hustles: ['Online therapy/coaching', 'Write a mental health blog', 'Create wellness content', 'Mindfulness workshops'],
    real_woman: { name: 'Dr. Yaba', emoji: '🧠', title: 'Clinical Psychologist', school: 'Howard University (Psychology)', quote: "Healing yourself first is the most radical act of service.", badge: 'Real Woman' },
    education_path: ["Bachelor's in Psychology or Social Work", "Master's degree (MSW, MFT, or Counseling)", 'Complete supervised clinical hours', 'Pass licensure exams'],
    career_ladder: [
      { title: 'Case Manager / Counselor Aide', years: '0–2 years', salary: '$35K–$55K', desc: 'Supporting licensed therapists and clients.' },
      { title: 'Licensed Counselor (LPC/LCSW)', years: '3–6 years', salary: '$55K–$85K', desc: 'Providing therapy under your own license.' },
      { title: 'Clinical Supervisor / Psychologist', years: '6–10 years', salary: '$80K–$130K', desc: 'Supervising others and leading clinical programs.' },
      { title: 'Director / Private Practice Owner', years: '10+ years', salary: '$100K–$250K+', desc: 'Running your own practice or organization.' },
    ],
    licensing: ['LPC, LCSW, or LMFT license', 'State licensure exam', 'Supervised clinical hours (2,000+)'],
    start_now: {
      classes: ['Psychology', 'AP Human Geography', 'Health', 'Sociology'],
      clubs: ['Peer Support Club', 'Mental Health Awareness Club', 'Key Club'],
      experience: ['Volunteer at a crisis hotline', 'Shadow a school counselor'],
      certifications: ['Mental Health First Aid', 'Youth Mental Health First Aid'],
      competitions: ['Psychology competitions', 'APA High School Research'],
    },
  },
  'Creative Arts': {
    glow_quote: "Your creativity is a superpower. The world needs your unique vision.",
    day_in_life: ['Sketch or design concepts', 'Client briefings and presentations', 'Fabric sourcing or production', 'Fittings and adjustments', 'Social media and portfolio updates'],
    skills: ['Creativity', 'Visual thinking', 'Trend awareness', 'Business acumen', 'Passion'],
    side_hustles: ['Sell custom designs on Etsy', 'Do personal styling', 'Create fashion content', 'Sell prints or digital art'],
    real_woman: { name: 'Aurora', emoji: '👗', title: 'Independent Fashion Designer', school: 'Parsons School of Design', quote: "Every stitch I make tells a story that was never told before.", badge: 'Real Woman' },
    education_path: ['Study art, design, or fashion in school', 'Build a portfolio of your work', 'Fashion design degree or art school', 'Intern at a fashion house or studio'],
    career_ladder: [
      { title: 'Design Intern / Assistant', years: '0–2 years', salary: '$25K–$45K', desc: 'Learning the industry from the ground up.' },
      { title: 'Junior Designer', years: '2–5 years', salary: '$45K–$80K', desc: 'Creating collections and developing your style.' },
      { title: 'Lead Designer / Art Director', years: '5–10 years', salary: '$80K–$150K', desc: 'Directing creative vision for brands.' },
      { title: 'Creative Director / Brand Owner', years: '10+ years', salary: '$150K–$500K+', desc: 'Running your own label or creative agency.' },
    ],
    licensing: ['No required license', 'Business license if self-employed', 'Copyright registration for original designs'],
    start_now: {
      classes: ['Art', 'Fashion Design', 'Textiles', 'Business'],
      clubs: ['Fashion Club', 'Art Club', 'DECA'],
      experience: ['Make and sell your own designs', 'Intern at a boutique'],
      certifications: ['Adobe Creative Suite courses', 'Fashion styling certifications'],
      competitions: ['Fashion design competitions', 'Art portfolio contests'],
    },
  },
  Finance: {
    glow_quote: "Money is power — and teaching others to manage it is even more powerful.",
    day_in_life: ['Review client portfolios', 'Market analysis and research', 'Client financial planning meetings', 'Process transactions and reports', 'Stay current on financial news'],
    skills: ['Math', 'Analysis', 'Trustworthiness', 'Communication', 'Risk assessment'],
    side_hustles: ['Personal finance coaching', 'Tax prep services', 'Investment blog/newsletter', 'Financial literacy workshops'],
    real_woman: { name: 'Arlan', emoji: '💳', title: 'Venture Capitalist', school: 'Self-taught + University of Houston', quote: "I built a VC fund while homeless. The obstacles are real — but not the end.", badge: 'Real Woman' },
    education_path: ['Take math and economics classes seriously', 'Get a degree in Finance, Economics, or Business', 'Get Series 7 and Series 63 licenses', 'Build experience through internships'],
    career_ladder: [
      { title: 'Bank Teller / Financial Analyst Intern', years: '0–2 years', salary: '$35K–$55K', desc: 'Learning financial systems and client relationships.' },
      { title: 'Financial Advisor / Analyst', years: '2–5 years', salary: '$60K–$100K', desc: 'Managing portfolios and advising clients.' },
      { title: 'Senior Advisor / Investment Manager', years: '5–10 years', salary: '$100K–$200K', desc: 'Leading high-value client relationships.' },
      { title: 'CFO / Partner / Wealth Manager', years: '10+ years', salary: '$200K–$1M+', desc: 'Top financial leadership roles.' },
    ],
    licensing: ['Series 7 license', 'Series 63 license', 'CFP (Certified Financial Planner)'],
    start_now: {
      classes: ['AP Economics', 'Statistics', 'Business Math', 'Accounting'],
      clubs: ['DECA', 'Investment Club', 'Junior Achievement'],
      experience: ['Open and manage a savings account', 'Intern at a bank or financial firm'],
      certifications: ['Google Finance basics', 'Khan Academy investing courses'],
      competitions: ['Stock Market competitions', 'DECA Finance events'],
    },
  },
  Media: {
    glow_quote: "Your platform is your power — use it to tell stories that matter.",
    day_in_life: ['Content ideation and planning', 'Filming or recording', 'Editing and post-production', 'Publishing and scheduling', 'Engage with audience and brands'],
    skills: ['Storytelling', 'Content creation', 'Adaptability', 'Branding', 'Audience growth'],
    side_hustles: ['Brand deals and sponsorships', 'Sell merch or presets', 'Online courses or workshops', 'Freelance video editing'],
    real_woman: { name: 'Issa', emoji: '🎬', title: 'Actress, Writer & Producer', school: 'Stanford University (African/African-American Studies)', quote: "I'm rooting for everybody Black. Create your own lane.", badge: 'Real Woman' },
    education_path: ['Start creating content now — practice every day', 'Study communications, film, or journalism', 'Build your portfolio and social following', 'Network with industry professionals'],
    career_ladder: [
      { title: 'Content Creator / Intern', years: '0–2 years', salary: '$20K–$50K', desc: 'Building your brand and skills from scratch.' },
      { title: 'Digital Media Specialist', years: '2–5 years', salary: '$50K–$90K', desc: 'Creating content for brands or your own platform.' },
      { title: 'Media Director / Producer', years: '5–10 years', salary: '$90K–$180K', desc: 'Leading creative teams and major productions.' },
      { title: 'Media Executive / Brand Owner', years: '10+ years', salary: '$200K–$1M+', desc: 'Running your own media company or show.' },
    ],
    licensing: ['No required license', 'FCC license for broadcasting', 'Business license for media company'],
    start_now: {
      classes: ['Journalism', 'Film/Media Arts', 'English', 'Marketing'],
      clubs: ['School News/TV Station', 'Yearbook', 'Drama Club'],
      experience: ['Start a YouTube or TikTok channel', 'Write for school newspaper'],
      certifications: ['Adobe Premiere Pro', 'HubSpot Content Marketing', 'Google Digital Garage'],
      competitions: ['Film festivals', 'Journalism competitions', 'Podcast competitions'],
    },
  },
  Science: {
    glow_quote: "Every discovery starts with a girl who refused to stop asking why.",
    day_in_life: ['Design and run experiments', 'Analyze data and results', 'Write research papers', 'Collaborate with research teams', 'Present findings at conferences'],
    skills: ['Curiosity', 'Research skills', 'Data analysis', 'Precision', 'Persistence'],
    side_hustles: ['STEM tutoring', 'Science content creation', 'Grant writing consulting', 'Lab tech freelancing'],
    real_woman: { name: 'Kizzmekia', emoji: '🔬', title: 'NIH Vaccine Scientist', school: 'UNC Chapel Hill (Biology)', quote: "Science is not just for certain kinds of people. I belong here — and so do you.", badge: 'Real Woman' },
    education_path: ["Excel in biology, chemistry, and physics", "Get a Bachelor's in a science field", "Pursue a Master's or PhD for research roles", 'Publish research and apply for grants'],
    career_ladder: [
      { title: 'Research Assistant / Lab Tech', years: '0–3 years', salary: '$35K–$55K', desc: 'Assisting with experiments and data collection.' },
      { title: 'Research Scientist', years: '3–7 years', salary: '$60K–$100K', desc: 'Leading your own research projects.' },
      { title: 'Senior Scientist / Principal Investigator', years: '7–12 years', salary: '$100K–$160K', desc: 'Running labs and securing funding.' },
      { title: 'Chief Scientist / Research Director', years: '12+ years', salary: '$150K–$300K+', desc: 'Leading major scientific initiatives.' },
    ],
    licensing: ['Professional certifications in specialty', 'Lab safety certifications', 'IRB research approval'],
    start_now: {
      classes: ['AP Biology', 'AP Chemistry', 'AP Physics', 'Statistics'],
      clubs: ['Science Olympiad', 'STEM Club', 'Environmental Club'],
      experience: ['Enter a science fair', 'Intern at a research lab'],
      certifications: ['Lab safety training', 'CITI research ethics training'],
      competitions: ['Regeneron ISEF', 'Science Olympiad', 'Intel Science Fair'],
    },
  },
  Design: {
    glow_quote: "You don't just make things beautiful — you make them work better.",
    day_in_life: ['Client brief and concept meetings', 'Sketching and 3D modeling', 'Site visits and measurements', 'Present design proposals', 'Coordinate with contractors'],
    skills: ['Spatial thinking', 'Creativity', 'Technical drawing', 'Client communication', 'Software skills'],
    side_hustles: ['Freelance interior design', 'Virtual home staging', 'Sell design templates', 'E-design services'],
    real_woman: { name: 'Zaha', emoji: '🏛️', title: 'World-Renowned Architect', school: 'Architectural Association, London', quote: "I was told I couldn't do it. I did it anyway — and changed architecture forever.", badge: 'Real Woman' },
    education_path: ['Study art, drafting, and math in school', 'Get a Bachelor of Architecture (B.Arch) degree', 'Complete internship hours (IDP)', 'Pass the ARE licensing exam'],
    career_ladder: [
      { title: 'Design Intern / Drafter', years: '0–2 years', salary: '$35K–$55K', desc: 'Learning software and assisting senior designers.' },
      { title: 'Junior Architect / Designer', years: '2–6 years', salary: '$55K–$90K', desc: 'Working on client projects independently.' },
      { title: 'Project Architect / Lead Designer', years: '6–12 years', salary: '$90K–$130K', desc: 'Leading design projects from concept to completion.' },
      { title: 'Principal / Firm Owner', years: '12+ years', salary: '$130K–$300K+', desc: 'Running your own architecture or design firm.' },
    ],
    licensing: ['NCIDQ license (interior design)', 'ARE license (architecture)', 'State registration'],
    start_now: {
      classes: ['Art', 'Drafting/CAD', 'Geometry', 'Physics'],
      clubs: ['Architecture Club', 'Art Club', 'STEM Design Team'],
      experience: ['Redesign a room in your home', 'Create a design portfolio'],
      certifications: ['AutoCAD basics', 'SketchUp', 'Adobe Creative Suite'],
      competitions: ['SkillsUSA Architecture competitions', 'AIA student design contests'],
    },
  },
  'Beauty & Wellness': {
    glow_quote: "You don't just make people look beautiful — you make them feel it.",
    day_in_life: ['Set up station and review appointments', 'Client consultations', 'Provide beauty services', 'Build client relationships', 'Update social media portfolio'],
    skills: ['Artistic skill', 'Customer service', 'Attention to detail', 'Business skills', 'Trendspotting'],
    side_hustles: ['Build your own clientele', 'Sell beauty products', 'Teach beauty courses', 'Beauty content creation'],
    real_woman: { name: 'Lisa', emoji: '🌹', title: 'Beauty Brand Founder', school: 'Self-taught + Brooklyn entrepreneur', quote: "I started with $100 in my kitchen. You don't need permission to start.", badge: 'Real Woman' },
    education_path: ['Take cosmetology or esthetics in school if available', 'Enroll in a licensed beauty school or program', 'Get your state cosmetology/esthetics license', 'Build your client base and portfolio'],
    career_ladder: [
      { title: 'Beauty School Student / Apprentice', years: '0–1 years', salary: '$20K–$35K', desc: 'Learning your craft and building technique.' },
      { title: 'Licensed Beautician / Technician', years: '1–4 years', salary: '$35K–$70K', desc: 'Building a loyal client base.' },
      { title: 'Lead Artist / Salon Manager', years: '4–8 years', salary: '$60K–$100K', desc: 'Leading a team or specializing in high-end services.' },
      { title: 'Salon/Spa Owner / Brand Founder', years: '8+ years', salary: '$80K–$500K+', desc: 'Running your own beauty business empire.' },
    ],
    licensing: ['State cosmetology license', 'Esthetics license', 'Nail tech license (if applicable)'],
    start_now: {
      classes: ['Cosmetology (if offered)', 'Chemistry', 'Business', 'Art'],
      clubs: ['FCCLA', 'Entrepreneurship Club', 'Art Club'],
      experience: ['Practice on family and friends', 'Assist at a local salon'],
      certifications: ['Cosmetology school enrollment', 'Online makeup artistry courses'],
      competitions: ['SkillsUSA Cosmetology', 'Beauty industry showcases'],
    },
  },
  'Tech & Digital': {
    glow_quote: "You don't just use the internet — you build what's next on it.",
    day_in_life: ['Check analytics and performance metrics', 'Design or code new features', 'Team collaboration and reviews', 'Client or stakeholder calls', 'Learn new tools and trends'],
    skills: ['Design thinking', 'Digital tools', 'Creativity', 'Data literacy', 'Adaptability'],
    side_hustles: ['Freelance design or development', 'Social media management', 'Create digital products', 'YouTube/TikTok tutorials'],
    real_woman: { name: 'Bozoma', emoji: '📱', title: 'Chief Marketing Officer', school: 'Wesleyan University (Arts)', quote: "I walked into rooms where I wasn't expected — and owned them.", badge: 'Real Woman' },
    education_path: ['Learn design tools (Figma, Adobe) or coding languages', 'Get a degree or take online bootcamp courses', 'Build a portfolio of real projects', 'Apply for internships or freelance work'],
    career_ladder: [
      { title: 'Digital Intern / Junior Designer', years: '0–2 years', salary: '$40K–$65K', desc: 'Learning tools and building your first projects.' },
      { title: 'Designer / Developer / Analyst', years: '2–5 years', salary: '$65K–$110K', desc: 'Owning projects and building expertise.' },
      { title: 'Senior Specialist / Team Lead', years: '5–8 years', salary: '$100K–$160K', desc: 'Leading digital strategy and teams.' },
      { title: 'Director / VP of Digital', years: '8+ years', salary: '$160K–$300K+', desc: 'Driving digital transformation at scale.' },
    ],
    licensing: ['No required license', 'Google/Meta certifications', 'AWS or cloud certifications'],
    start_now: {
      classes: ['Computer Science', 'Graphic Design', 'Web Development', 'Marketing'],
      clubs: ['Coding Club', 'Digital Media Club', 'Girls Who Code'],
      experience: ['Build a personal website', 'Manage social media for a local business'],
      certifications: ['Google Digital Marketing', 'Meta Blueprint', 'Figma/Adobe certifications'],
      competitions: ['Hackathons', 'DECA Digital Marketing', 'SkillsUSA Web Design'],
    },
  },
  'Creative & Media': {
    glow_quote: "Your art can change hearts, shift culture, and move the world forward.",
    day_in_life: ['Morning vocal or physical warm-up', 'Rehearsals or recording sessions', 'Creative writing or concept work', 'Meetings with producers or agents', 'Promote on social media'],
    skills: ['Storytelling', 'Performance', 'Creativity', 'Resilience', 'Self-promotion'],
    side_hustles: ['Perform at local events', 'Teach music or dance', 'License your work', 'Brand deals and collabs'],
    real_woman: { name: 'Issa Rae', emoji: '🎭', title: 'Actress, Writer & Producer', school: 'Stanford University', quote: "I'm rooting for everybody Black. Create your own lane.", badge: 'Real Woman' },
    education_path: ['Start performing or creating NOW — build your craft early', 'Study performing arts, film, or creative writing', 'Build a portfolio, reel, or demo tape', 'Network and audition relentlessly'],
    career_ladder: [
      { title: 'Emerging Artist / Student', years: '0–3 years', salary: '$10K–$35K', desc: 'Building skills, a portfolio, and your first credits.' },
      { title: 'Working Artist / Creator', years: '3–7 years', salary: '$35K–$100K', desc: 'Booking gigs, growing your audience.' },
      { title: 'Established Artist / Director', years: '7–12 years', salary: '$80K–$500K', desc: 'Known name, consistent work, creative control.' },
      { title: 'Icon / Production Company Owner', years: '12+ years', salary: '$500K–$20M+', desc: 'Legendary status and your own empire.' },
    ],
    licensing: ['SAG-AFTRA membership (acting)', 'ASCAP/BMI registration (music)', 'Business license for production company'],
    start_now: {
      classes: ['Drama', 'Music', 'Creative Writing', 'Film Production'],
      clubs: ['Theater Club', 'A cappella / Choir', 'Film Club', 'Dance Team'],
      experience: ['Perform in school productions', 'Start a YouTube or podcast'],
      certifications: ['Acting workshops', 'Music production courses', 'Adobe Premiere basics'],
      competitions: ['Drama competitions', 'Film festivals', 'Poetry slams'],
    },
  },
  'Education & Social Impact': {
    glow_quote: "You change the world one person, one policy, one community at a time.",
    day_in_life: ['Strategy and planning meetings', 'Community outreach and events', 'Grant writing and fundraising', 'Team management and training', 'Advocacy and policy work'],
    skills: ['Advocacy', 'Communication', 'Empathy', 'Leadership', 'Community building'],
    side_hustles: ['Consulting for nonprofits', 'Public speaking engagements', 'Write a social justice blog', 'Community workshop facilitation'],
    real_woman: { name: 'Stacey', emoji: '🌍', title: 'Politician & Voting Rights Activist', school: 'Yale Law School', quote: "When you show up for your community, your community shows up for you.", badge: 'Real Woman' },
    education_path: ['Get involved in community service now', 'Study Social Work, Public Policy, or Education', 'Build experience with nonprofits or government', "Pursue a Master's for leadership roles"],
    career_ladder: [
      { title: 'Community Volunteer / Intern', years: '0–2 years', salary: '$25K–$45K', desc: 'Learning the landscape of community work.' },
      { title: 'Program Coordinator / Case Manager', years: '2–5 years', salary: '$45K–$70K', desc: 'Running programs and supporting communities.' },
      { title: 'Program Director / Manager', years: '5–10 years', salary: '$70K–$110K', desc: 'Leading teams and major initiatives.' },
      { title: 'Executive Director / Elected Official', years: '10+ years', salary: '$90K–$200K+', desc: 'Leading organizations or representing constituents.' },
    ],
    licensing: ['LCSW license (social work)', 'Teaching certification', 'Nonprofit management credentials'],
    start_now: {
      classes: ['Social Studies', 'Government/Civics', 'Psychology', 'English'],
      clubs: ['Student Government', 'Key Club', 'Model UN', 'Volunteer Corps'],
      experience: ['Volunteer at a local nonprofit', 'Organize a community event'],
      certifications: ['Nonprofit leadership courses', 'Grant writing workshops'],
      competitions: ['We the People civics competition', 'Youth activism awards'],
    },
  },
  'Law & Justice': {
    glow_quote: "Justice isn't just a word — it's a calling. Answer it.",
    day_in_life: ['Case briefings and evidence review', 'Courtroom appearances or hearings', 'Interviews and investigations', 'Legal research and filings', 'Community outreach'],
    skills: ['Critical thinking', 'Ethics', 'Investigation', 'Communication', 'Attention to detail'],
    side_hustles: ['Legal consulting', 'Paralegal freelance', 'Write about justice topics', 'Serve on community boards'],
    real_woman: { name: 'Ketanji Brown', emoji: '🏛️', title: 'Supreme Court Justice', school: 'Harvard Law School', quote: "I am the dream and the hope of the enslaved — standing in this seat.", badge: 'Real Woman' },
    education_path: ['Join mock trial and debate in high school', 'Get a 4-year degree followed by law school', 'Specialize in criminal law, civil rights, or public service', 'Pass the bar and build courtroom experience'],
    career_ladder: [
      { title: 'Paralegal / Law Clerk', years: '0–3 years', salary: '$40K–$65K', desc: 'Supporting legal teams with research and filing.' },
      { title: 'Attorney / Public Defender', years: '3–7 years', salary: '$65K–$150K', desc: 'Practicing law and representing clients.' },
      { title: 'Senior Attorney / Detective', years: '7–12 years', salary: '$100K–$200K', desc: 'Leading complex cases and investigations.' },
      { title: 'Judge / Chief Prosecutor / Director', years: '12+ years', salary: '$150K–$300K+', desc: 'Top leadership in legal and justice systems.' },
    ],
    licensing: ['JD degree and bar exam', 'Law enforcement training academy', 'Federal agent credentials'],
    start_now: {
      classes: ['Government', 'AP US History', 'Debate', 'English/Writing'],
      clubs: ['Mock Trial', 'Debate Team', 'Model UN', 'Student Court'],
      experience: ['Intern at a courthouse or law firm', 'Participate in police explorer programs'],
      certifications: ['LSAT prep courses', 'Criminal justice online courses'],
      competitions: ['Mock Trial tournaments', 'We the People competitions'],
    },
  },
  'Trades & Entrepreneurship': {
    glow_quote: "Your hands build the world — and your business mind owns it.",
    day_in_life: ['Review project plans and schedules', 'On-site work and inspections', 'Client meetings and estimates', 'Manage crew and subcontractors', 'Handle invoicing and finances'],
    skills: ['Technical skills', 'Problem solving', 'Physical stamina', 'Business sense', 'Reliability'],
    side_hustles: ['Start your own contracting business', 'Teach trade skills workshops', 'Flip and renovate properties', 'Consult on trade projects'],
    real_woman: { name: 'Felicia', emoji: '🔧', title: 'Master Electrician & Business Owner', school: 'Vocational Technical High School + Apprenticeship', quote: "I built a 6-figure business with my hands and my hustle.", badge: 'Real Woman' },
    education_path: ['Take vocational or trade classes in high school', 'Complete a trade apprenticeship program', 'Get your journeyman then master license', 'Start your own business'],
    career_ladder: [
      { title: 'Apprentice', years: '0–4 years', salary: '$35K–$55K', desc: 'Learning your trade under a licensed professional.' },
      { title: 'Journeyman / Technician', years: '4–8 years', salary: '$55K–$85K', desc: 'Working independently on job sites.' },
      { title: 'Master Tradesperson', years: '8–12 years', salary: '$80K–$120K', desc: 'Top of your trade, able to train others.' },
      { title: 'Business Owner / Contractor', years: '12+ years', salary: '$100K–$500K+', desc: 'Running your own trade business.' },
    ],
    licensing: ['Journeyman license', 'Master tradesperson license', 'OSHA safety certifications'],
    start_now: {
      classes: ['Shop/Trade classes', 'Math', 'Physics', 'Business'],
      clubs: ['SkillsUSA', 'VICA', 'Construction Club'],
      experience: ['Work with a family member or neighbor on projects', 'Volunteer for Habitat for Humanity'],
      certifications: ['OSHA 10 safety card', 'First Aid/CPR', 'Trade apprenticeship programs'],
      competitions: ['SkillsUSA trade competitions', 'National Technical Honor Society'],
    },
  },
};

const CAREER_OVERRIDES = {
  1: { glow_quote: "You create your own rules, your own schedule, and your own legacy.", related_ids: [32, 33, 28] },
  14: { glow_quote: "There is no greater honor than being trusted with someone's life.", related_ids: [15, 16, 30] },
  27: { glow_quote: "The law is the most powerful tool for change — and it belongs to you.", related_ids: [74, 75, 78] },
  28: { glow_quote: "The apps you use every day were built by someone who started exactly where you are.", related_ids: [49, 51, 53] },
};

export const CAREERS = [
  { id: 1, emoji: '👑', category: 'Business', exp: 'Executive', title: 'Entrepreneur / Business Owner', salary: '$30K – $1M+', desc: 'Build something from nothing. Create jobs, solve problems, and be your own boss.' },
  { id: 2, emoji: '📣', category: 'Business', exp: 'Mid Level', title: 'Marketing Manager', salary: '$65K – $150K+', desc: 'Lead marketing strategy, campaigns, and brand growth for companies and organizations.' },
  { id: 3, emoji: '🤝', category: 'Business', exp: 'Mid Level', title: 'Human Resources Manager', salary: '$65K – $130K+', desc: 'Manage the most important asset of any company — its people.' },
  { id: 4, emoji: '🧾', category: 'Business', exp: 'Mid Level', title: 'Accountant / CPA', salary: '$60K – $150K+', desc: 'Master the language of money — and help individuals and businesses manage, save, and grow their finances.' },
  { id: 5, emoji: '🏠', category: 'Business', exp: 'Mid Level', title: 'Mortgage Loan Officer', salary: '$50K – $200K+', desc: 'Help people achieve the dream of homeownership by guiding them through the mortgage process.' },
  { id: 6, emoji: '📋', category: 'Business', exp: 'Mid Level', title: 'Project Manager', salary: '$70K – $150K+', desc: 'Lead teams, manage timelines, and deliver results — in any industry.' },
  { id: 7, emoji: '🎉', category: 'Business', exp: 'Entry Level', title: 'Event Planner', salary: '$40K – $120K+', desc: 'Create unforgettable experiences — from weddings to corporate galas to music festivals.' },
  { id: 8, emoji: '💼', category: 'Business', exp: 'Entry Level', title: 'Sales Executive', salary: '$50K – $250K+', desc: 'Drive revenue, build relationships, and master the art of persuasion in any industry.' },
  { id: 9, emoji: '📊', category: 'Business', exp: 'Senior Level', title: 'Business Consultant', salary: '$70K – $300K+', desc: 'Help companies solve problems, improve performance, and grow — and get paid very well to do it.' },
  { id: 10, emoji: '📱', category: 'Business', exp: 'Entry Level', title: 'Executive Assistant', salary: '$55K – $120K+', desc: 'Be the right hand of top executives — managing schedules, communications, and making things happen.' },
  { id: 11, emoji: '⚙️', category: 'Business', exp: 'Mid Level', title: 'Operations Manager', salary: '$65K – $140K+', desc: 'Keep businesses running smoothly by optimizing processes, managing teams, and driving efficiency.' },
  { id: 12, emoji: '📢', category: 'Business', exp: 'Entry Level', title: 'Public Relations Specialist', salary: '$50K – $130K+', desc: 'Shape how the world sees brands, celebrities, and organizations through strategic communication.' },
  { id: 13, emoji: '🔍', category: 'Business', exp: 'Entry Level', title: 'Recruiter', salary: '$50K – $150K+', desc: 'Connect talented people with their dream jobs and help companies build winning teams.' },
  { id: 14, emoji: '🩺', category: 'Healthcare', exp: 'Executive', title: 'Doctor / Physician', salary: '$150K – $400K+', desc: 'Save lives, heal people, and make a real difference in your community every single day.' },
  { id: 15, emoji: '💉', category: 'Healthcare', exp: 'Mid Level', title: 'Nurse / Nurse Practitioner', salary: '$60K – $130K+', desc: 'Be the heartbeat of healthcare — the person patients trust most during their hardest moments.' },
  { id: 16, emoji: '🤰', category: 'Healthcare', exp: 'Executive', title: 'OB-GYN', salary: '$200K – $400K+', desc: "Specialize in women's reproductive health, deliver babies, and be a trusted advocate for women." },
  { id: 17, emoji: '🦷', category: 'Healthcare', exp: 'Executive', title: 'Dentist', salary: '$150K – $350K+', desc: 'Protect smiles, relieve pain, and build a highly profitable practice as a dental professional.' },
  { id: 18, emoji: '😁', category: 'Healthcare', exp: 'Executive', title: 'Orthodontist', salary: '$200K – $400K+', desc: 'Straighten smiles and transform confidence through braces, aligners, and orthodontic treatment.' },
  { id: 19, emoji: '💊', category: 'Healthcare', exp: 'Senior Level', title: 'Pharmacist', salary: '$120K – $160K+', desc: 'Be the medication expert patients rely on — ensuring safe, effective drug therapy and counseling.' },
  { id: 20, emoji: '🏃', category: 'Healthcare', exp: 'Mid Level', title: 'Physical Therapist', salary: '$75K – $110K+', desc: 'Help patients recover from injuries and surgeries to regain movement, strength, and quality of life.' },
  { id: 21, emoji: '🤝', category: 'Healthcare', exp: 'Mid Level', title: 'Occupational Therapist', salary: '$70K – $110K+', desc: 'Help people recover from injuries, disabilities, or illness to regain independence in daily life.' },
  { id: 22, emoji: '🔊', category: 'Healthcare', exp: 'Entry Level', title: 'Ultrasound Technician', salary: '$60K – $100K+', desc: 'Use imaging technology to help diagnose conditions and capture emotional moments in medicine.' },
  { id: 23, emoji: '🩻', category: 'Healthcare', exp: 'Entry Level', title: 'Radiology Technician', salary: '$55K – $95K+', desc: 'Perform X-rays, CT scans, and MRIs that help doctors diagnose and treat patients.' },
  { id: 24, emoji: '🗣️', category: 'Healthcare', exp: 'Mid Level', title: 'Speech Pathologist', salary: '$65K – $110K+', desc: 'Help children and adults overcome speech, language, and swallowing disorders.' },
  { id: 25, emoji: '🥗', category: 'Healthcare', exp: 'Entry Level', title: 'Nutritionist / Dietitian', salary: '$50K – $100K+', desc: 'Help people transform their health through food, nutrition education, and personalized meal planning.' },
  { id: 26, emoji: '🏥', category: 'Healthcare', exp: 'Entry Level', title: 'Medical Assistant', salary: '$35K – $55K+', desc: 'Support physicians and nurses in clinical and administrative tasks — a fast-entry path into healthcare.' },
  { id: 27, emoji: '⚖️', category: 'Law', exp: 'Senior Level', title: 'Lawyer / Attorney', salary: '$70K – $300K+', desc: "Fight for justice, protect people's rights, and use your voice to change the world." },
  { id: 28, emoji: '💻', category: 'Technology', exp: 'Mid Level', title: 'Software Engineer / Tech', salary: '$80K – $300K+', desc: 'Build the apps, platforms, and systems that billions of people use every day.' },
  { id: 29, emoji: '📚', category: 'Education', exp: 'Entry Level', title: 'Teacher / Educator', salary: '$40K – $90K+', desc: 'Shape the next generation. Every great leader had a teacher who believed in them.' },
  { id: 30, emoji: '🧠', category: 'Mental Health', exp: 'Mid Level', title: 'Psychologist / Therapist', salary: '$60K – $150K+', desc: 'Help people heal, grow, and become the best versions of themselves. Mental health is everything.' },
  { id: 31, emoji: '👗', category: 'Creative Arts', exp: 'Entry Level', title: 'Fashion Designer / Stylist', salary: '$35K – $200K+', desc: 'Turn creativity into a career. Design clothes, style celebrities, or build your own fashion brand.' },
  { id: 32, emoji: '💳', category: 'Finance', exp: 'Mid Level', title: 'Financial Advisor / Banker', salary: '$60K – $250K+', desc: 'Help people build wealth, plan for the future, and achieve financial freedom.' },
  { id: 33, emoji: '🎬', category: 'Media', exp: 'Entry Level', title: 'Media / Content Creator', salary: '$20K – $1M+', desc: 'Build a platform, tell your story, and influence millions through content creation.' },
  { id: 34, emoji: '🔬', category: 'Science', exp: 'Mid Level', title: 'Scientist / Researcher', salary: '$55K – $150K+', desc: 'Discover cures, solve global problems, and push the boundaries of what humanity knows.' },
  { id: 35, emoji: '🏛️', category: 'Design', exp: 'Mid Level', title: 'Architect / Interior Designer', salary: '$50K – $130K+', desc: 'Design the spaces where people live, work, learn, and dream. Shape the world around you.' },
  { id: 36, emoji: '💄', category: 'Beauty & Wellness', exp: 'Entry Level', title: 'Makeup Artist', salary: '$35K – $150K+', desc: 'Transform faces, boost confidence, and turn artistry into a thriving career.' },
  { id: 37, emoji: '🌸', category: 'Beauty & Wellness', exp: 'Entry Level', title: 'Esthetician', salary: '$35K – $90K+', desc: 'Specialize in skincare treatments, facials, and helping clients achieve their best skin ever.' },
  { id: 38, emoji: '✂️', category: 'Beauty & Wellness', exp: 'Entry Level', title: 'Hairstylist', salary: '$30K – $120K+', desc: 'Create stunning hair transformations and build a loyal clientele.' },
  { id: 39, emoji: '💅', category: 'Beauty & Wellness', exp: 'Entry Level', title: 'Nail Technician', salary: '$28K – $80K+', desc: 'Master the art of nail design and build a creative, flexible career with loyal clients.' },
  { id: 40, emoji: '👁️', category: 'Beauty & Wellness', exp: 'Entry Level', title: 'Lash Technician', salary: '$35K – $100K+', desc: 'Specialize in eyelash extensions and become a sought-after beauty professional.' },
  { id: 41, emoji: '🪒', category: 'Beauty & Wellness', exp: 'Entry Level', title: 'Barber', salary: '$35K – $100K+', desc: 'Master the art of cuts, fades, and grooming — a high-demand, recession-proof career.' },
  { id: 42, emoji: '🧴', category: 'Beauty & Wellness', exp: 'Executive', title: 'Skincare Brand Owner', salary: '$40K – $500K+', desc: 'Create and sell your own skincare line — from formulation to branding to loyal customers.' },
  { id: 43, emoji: '🌹', category: 'Beauty & Wellness', exp: 'Mid Level', title: 'Perfumer', salary: '$45K – $200K+', desc: 'Create signature fragrances for luxury brands, celebrities, or your own perfume line.' },
  { id: 44, emoji: '🪞', category: 'Beauty & Wellness', exp: 'Mid Level', title: 'Image Consultant', salary: '$45K – $150K+', desc: 'Help clients discover their personal style, build confidence, and present their best selves.' },
  { id: 45, emoji: '👗', category: 'Beauty & Wellness', exp: 'Mid Level', title: 'Personal Stylist', salary: '$40K – $200K+', desc: 'Curate outfits and looks for celebrities, executives, and everyday clients.' },
  { id: 46, emoji: '🔬', category: 'Beauty & Wellness', exp: 'Senior Level', title: 'Cosmetic Chemist', salary: '$60K – $130K+', desc: 'Develop the formulas behind your favorite beauty products — from serums to foundations.' },
  { id: 47, emoji: '🧖', category: 'Beauty & Wellness', exp: 'Executive', title: 'Spa Owner', salary: '$50K – $300K+', desc: 'Create a luxury wellness destination where clients come to relax, rejuvenate, and feel their best.' },
  { id: 48, emoji: '📸', category: 'Beauty & Wellness', exp: 'Entry Level', title: 'Beauty Influencer', salary: '$20K – $1M+', desc: 'Build a loyal audience by sharing beauty tips, tutorials, and product reviews across social platforms.' },
  { id: 49, emoji: '🎨', category: 'Tech & Digital', exp: 'Mid Level', title: 'UX Designer', salary: '$75K – $150K+', desc: 'Design the apps and websites people love to use — combining psychology, design, and technology.' },
  { id: 50, emoji: '🖌️', category: 'Tech & Digital', exp: 'Entry Level', title: 'Graphic Designer', salary: '$45K – $100K+', desc: 'Create visual identities, marketing materials, and digital art that makes brands come alive.' },
  { id: 51, emoji: '📱', category: 'Tech & Digital', exp: 'Mid Level', title: 'App Developer', salary: '$80K – $160K+', desc: 'Build the mobile apps that people use every day — from social media to health trackers to games.' },
  { id: 52, emoji: '📈', category: 'Tech & Digital', exp: 'Entry Level', title: 'Data Analyst', salary: '$65K – $130K+', desc: 'Turn raw data into insights that drive business decisions — one of the most in-demand skills of our time.' },
  { id: 53, emoji: '🔐', category: 'Tech & Digital', exp: 'Mid Level', title: 'Cybersecurity Analyst', salary: '$80K – $160K+', desc: 'Protect companies and individuals from hackers, data breaches, and cyber threats.' },
  { id: 54, emoji: '📲', category: 'Tech & Digital', exp: 'Entry Level', title: 'Social Media Manager', salary: '$45K – $100K+', desc: 'Build and grow brand presence across social platforms through strategic content and community.' },
  { id: 55, emoji: '📈', category: 'Tech & Digital', exp: 'Entry Level', title: 'Digital Marketer', salary: '$55K – $130K+', desc: 'Drive traffic, leads, and sales through SEO, ads, email marketing, and digital strategy.' },
  { id: 56, emoji: '🎬', category: 'Tech & Digital', exp: 'Entry Level', title: 'Content Creator', salary: '$20K – $1M+', desc: 'Build a personal brand and audience by creating videos, posts, and content that inspires.' },
  { id: 57, emoji: '🎞️', category: 'Tech & Digital', exp: 'Entry Level', title: 'Video Editor', salary: '$45K – $120K+', desc: 'Transform raw footage into compelling stories for YouTube, film, TV, and social media.' },
  { id: 58, emoji: '🌐', category: 'Tech & Digital', exp: 'Entry Level', title: 'Web Designer', salary: '$50K – $120K+', desc: 'Create beautiful, functional websites that help businesses and creators look professional online.' },
  { id: 59, emoji: '🤖', category: 'Tech & Digital', exp: 'Mid Level', title: 'AI Prompt Engineer', salary: '$60K – $200K+', desc: 'Master the art of communicating with AI — one of the newest and most exciting careers in tech.' },
  { id: 60, emoji: '🎮', category: 'Tech & Digital', exp: 'Mid Level', title: 'Game Designer', salary: '$60K – $150K+', desc: 'Create the worlds, characters, and mechanics behind video games that millions of people play.' },
  { id: 61, emoji: '🎭', category: 'Creative & Media', exp: 'Entry Level', title: 'Actress', salary: '$20K – $20M+', desc: 'Bring characters to life on stage, film, and television — and inspire audiences around the world.' },
  { id: 62, emoji: '🎤', category: 'Creative & Media', exp: 'Entry Level', title: 'Singer', salary: '$20K – $50M+', desc: 'Use your voice to move people, tell stories, and build a career in music.' },
  { id: 63, emoji: '💃', category: 'Creative & Media', exp: 'Entry Level', title: 'Dancer / Choreographer', salary: '$25K – $200K+', desc: 'Express yourself through movement and build a career in performance, choreography, or dance education.' },
  { id: 64, emoji: '✍️', category: 'Creative & Media', exp: 'Entry Level', title: 'Author / Writer', salary: '$20K – $1M+', desc: 'Tell stories, share knowledge, and build a legacy through books, journalism, and creative writing.' },
  { id: 65, emoji: '📰', category: 'Creative & Media', exp: 'Entry Level', title: 'Journalist / Reporter', salary: '$35K – $100K+', desc: 'Uncover the truth, break stories, and hold the powerful accountable through investigative reporting.' },
  { id: 66, emoji: '🎙️', category: 'Creative & Media', exp: 'Entry Level', title: 'Podcast Host', salary: '$20K – $500K+', desc: 'Build an audience through audio storytelling and become a voice people tune in to every week.' },
  { id: 67, emoji: '📷', category: 'Creative & Media', exp: 'Entry Level', title: 'Photographer', salary: '$30K – $150K+', desc: "Capture the world's most powerful moments through a lens." },
  { id: 68, emoji: '🏫', category: 'Education & Social Impact', exp: 'Senior Level', title: 'School Principal', salary: '$80K – $130K+', desc: 'Lead a school community, support teachers, and shape the culture that educates generations.' },
  { id: 69, emoji: '🤲', category: 'Education & Social Impact', exp: 'Entry Level', title: 'Social Worker', salary: '$45K – $80K+', desc: 'Advocate for vulnerable people and communities — one of the most impactful careers you can choose.' },
  { id: 70, emoji: '🌍', category: 'Education & Social Impact', exp: 'Senior Level', title: 'Nonprofit Director', salary: '$60K – $150K+', desc: 'Lead an organization that creates real change in your community and the world.' },
  { id: 71, emoji: '🏛️', category: 'Education & Social Impact', exp: 'Mid Level', title: 'Policy Analyst', salary: '$60K – $130K+', desc: "Shape the laws and policies that affect millions of people's lives." },
  { id: 72, emoji: '👩‍🏫', category: 'Education & Social Impact', exp: 'Senior Level', title: 'College Professor', salary: '$60K – $150K+', desc: 'Inspire the next generation of leaders at universities while advancing your field.' },
  { id: 73, emoji: '🌱', category: 'Education & Social Impact', exp: 'Entry Level', title: 'Community Organizer', salary: '$35K – $80K+', desc: 'Mobilize communities, advocate for change, and build power from the ground up.' },
  { id: 74, emoji: '🏛️', category: 'Law & Justice', exp: 'Executive', title: 'Judge', salary: '$100K – $250K+', desc: 'Preside over court proceedings, interpret the law, and ensure justice is served fairly.' },
  { id: 75, emoji: '🔍', category: 'Law & Justice', exp: 'Mid Level', title: 'Criminal Investigator / Detective', salary: '$60K – $120K+', desc: 'Solve crimes, bring justice to victims, and protect communities as a detective or federal agent.' },
  { id: 76, emoji: '📜', category: 'Law & Justice', exp: 'Entry Level', title: 'Paralegal', salary: '$45K – $80K+', desc: 'Support attorneys, conduct legal research, and build a career at the heart of the justice system.' },
  { id: 77, emoji: '🚔', category: 'Law & Justice', exp: 'Entry Level', title: 'Law Enforcement Officer', salary: '$50K – $100K+', desc: 'Protect and serve your community as a police officer, marshal, or federal agent.' },
  { id: 78, emoji: '🛡️', category: 'Law & Justice', exp: 'Senior Level', title: 'Civil Rights Attorney', salary: '$50K – $200K+', desc: 'Fight for equality, justice, and the rights of people who have been wronged by the system.' },
  { id: 79, emoji: '🔧', category: 'Trades & Entrepreneurship', exp: 'Entry Level', title: 'Electrician', salary: '$50K – $100K+', desc: 'Power homes, businesses, and infrastructure — a skilled trade with strong job security and great pay.' },
  { id: 80, emoji: '🏗️', category: 'Trades & Entrepreneurship', exp: 'Mid Level', title: 'Construction Manager', salary: '$75K – $150K+', desc: 'Oversee building projects from blueprint to completion — managing people, timelines, and budgets.' },
  { id: 81, emoji: '🛠️', category: 'Trades & Entrepreneurship', exp: 'Entry Level', title: 'Plumber', salary: '$55K – $100K+', desc: 'Master a trade that will always be in demand — and build a business or franchise of your own.' },
  { id: 82, emoji: '🚗', category: 'Trades & Entrepreneurship', exp: 'Entry Level', title: 'Auto Technician', salary: '$40K – $90K+', desc: 'Keep vehicles running and build a career in one of the most in-demand skilled trades.' },
  { id: 83, emoji: '👩‍💼', category: 'Trades & Entrepreneurship', exp: 'Senior Level', title: 'Franchise Owner', salary: '$60K – $500K+', desc: 'Own your business with the backing of a proven brand — the entrepreneurial path with a safety net.' },
  { id: 84, emoji: '🍽️', category: 'Trades & Entrepreneurship', exp: 'Mid Level', title: 'Restaurant Owner', salary: '$35K – $500K+', desc: 'Build your own food empire — from a local diner to a franchise chain.' },
];

export function getCareerData(career) {
  const base = DEFAULT_DATA[career.category] || DEFAULT_DATA['Business'];
  const override = CAREER_OVERRIDES[career.id] || {};
  const relatedIds = override.related_ids || CAREERS.filter(c => c.category === career.category && c.id !== career.id).slice(0, 3).map(c => c.id);
  const related = relatedIds.map(id => CAREERS.find(c => c.id === id)).filter(Boolean);
  return { ...base, ...override, related };
}