export const CHALLENGES = [
  {
    id: 'confidence',
    name: 'Confidence',
    emoji: '👑',
    color: '#FF1F8E',
    gradient: 'from-pink-600 to-rose-600',
    subtitle: 'Know Who You Are · Show Up · Live Out Loud',
    description: 'Build unshakeable confidence by knowing your worth, showing up authentically, and living out loud.',
    phases: {
      foundation: {
        name: 'Phase 1: Know Who You Are',
        days: [
          { day: 1, task: 'Write down 3 things you love about yourself', points: 10 },
          { day: 2, task: 'Stand tall and practice power posing for 2 minutes', points: 10 },
          { day: 3, task: 'Say one positive affirmation in the mirror', points: 10 },
          { day: 4, task: 'Write about a time you felt proud of yourself', points: 15 },
          { day: 5, task: 'Compliment yourself out loud 3 times today', points: 10 },
          { day: 6, task: 'Identify one limiting belief and challenge it', points: 15 },
          { day: 7, task: 'Wear something that makes you feel powerful', points: 10 },
          { day: 8, task: 'Speak up in class or a group conversation', points: 15 },
          { day: 9, task: 'Write down your top 5 strengths', points: 10 },
          { day: 10, task: 'Practice saying "no" to something that doesn\'t align with your values', points: 20 },
        ],
      },
      growth: {
        name: 'Phase 2: Show Up',
        days: [
          { day: 11, task: 'Introduce yourself to someone new', points: 20 },
          { day: 12, task: 'Share an opinion in class even if others might disagree', points: 20 },
          { day: 13, task: 'Post or share something authentic on social media', points: 15 },
          { day: 14, task: 'Try something you\'ve been afraid to try', points: 25 },
          { day: 15, task: 'Ask a question in class or at an event', points: 15 },
          { day: 16, task: 'Celebrate someone else\'s win genuinely', points: 10 },
          { day: 17, task: 'Do something that scares you (but is safe)', points: 25 },
          { day: 18, task: 'Share a creative project or idea with others', points: 20 },
          { day: 19, task: 'Stand up for yourself or someone else', points: 25 },
          { day: 20, task: 'Show up fully to an event without hiding', points: 20 },
        ],
      },
      mastery: {
        name: 'Phase 3: Live Out Loud',
        days: [
          { day: 21, task: 'Lead a project or initiative', points: 30 },
          { day: 22, task: 'Share your story to inspire someone', points: 25 },
          { day: 23, task: 'Mentor or help someone younger', points: 20 },
          { day: 24, task: 'Take up space unapologetically', points: 20 },
          { day: 25, task: 'Express your authentic style boldly', points: 15 },
          { day: 26, task: 'Speak your truth even when it\'s hard', points: 30 },
          { day: 27, task: 'Celebrate how far you\'ve come', points: 15 },
          { day: 28, task: 'Set a boundary with love and confidence', points: 25 },
          { day: 29, task: 'Own your achievements without downplaying', points: 20 },
          { day: 30, task: 'Declare who you are and who you\'re becoming', points: 30 },
        ],
      },
    },
  },
  {
    id: 'faith',
    name: 'Faith & Purpose',
    emoji: '🙏',
    color: '#8B5CF6',
    gradient: 'from-violet-600 to-purple-600',
    subtitle: 'Root Yourself · Align Your Life · Walk It Out',
    description: 'Deepen your faith, discover your purpose, and align your daily actions with your spiritual foundation.',
    phases: {
      foundation: {
        name: 'Phase 1: Root Yourself',
        days: [
          { day: 1, task: 'Spend 5 minutes in prayer or meditation', points: 10 },
          { day: 2, task: 'Write down what faith means to you', points: 15 },
          { day: 3, task: 'Read an inspiring spiritual passage', points: 10 },
          { day: 4, task: 'Journal about your purpose or calling', points: 20 },
          { day: 5, task: 'Practice gratitude for 3 blessings', points: 10 },
          { day: 6, task: 'Identify your core values', points: 15 },
          { day: 7, task: 'Spend time in nature connecting with your creator', points: 15 },
          { day: 8, task: 'Write a letter to your future self', points: 20 },
          { day: 9, task: 'Meditate on a verse or quote that inspires you', points: 10 },
          { day: 10, task: 'Forgive yourself for one past mistake', points: 20 },
        ],
      },
      growth: {
        name: 'Phase 2: Align Your Life',
        days: [
          { day: 11, task: 'Align one habit with your values', points: 20 },
          { day: 12, task: 'Serve someone without expecting anything back', points: 25 },
          { day: 13, task: 'Fast from something distracting for a day', points: 20 },
          { day: 14, task: 'Attend a spiritual service or gathering', points: 20 },
          { day: 15, task: 'Share your faith journey with someone', points: 25 },
          { day: 16, task: 'Create a morning spiritual practice', points: 20 },
          { day: 17, task: 'Give generously (time, money, or energy)', points: 20 },
          { day: 18, task: 'Write down how you want to impact the world', points: 25 },
          { day: 19, task: 'Release one worry through prayer/meditation', points: 15 },
          { day: 20, task: 'Align your schedule with your priorities', points: 20 },
        ],
      },
      mastery: {
        name: 'Phase 3: Walk It Out',
        days: [
          { day: 21, task: 'Lead a prayer, meditation, or discussion', points: 30 },
          { day: 22, task: 'Mentor someone in their faith journey', points: 25 },
          { day: 23, task: 'Take a leap of faith on something important', points: 30 },
          { day: 24, task: 'Share a testimony of growth', points: 20 },
          { day: 25, task: 'Create a vision board for your purpose', points: 20 },
          { day: 26, task: 'Make a decision based on faith not fear', points: 30 },
          { day: 27, task: 'Bless someone who can\'t repay you', points: 20 },
          { day: 28, task: 'Stand firm in your beliefs despite pressure', points: 25 },
          { day: 29, task: 'Celebrate how your faith has grown', points: 15 },
          { day: 30, task: 'Commit to walking in your purpose daily', points: 30 },
        ],
      },
    },
  },
  {
    id: 'academic',
    name: 'Academic Excellence',
    emoji: '📚',
    color: '#3B82F6',
    gradient: 'from-blue-600 to-indigo-600',
    subtitle: 'Build Your System · Level Up · Own Your Future',
    description: 'Master your studies, build effective systems, and take ownership of your academic future.',
    phases: {
      foundation: {
        name: 'Phase 1: Build Your System',
        days: [
          { day: 1, task: 'Organize your study space', points: 10 },
          { day: 2, task: 'Create a weekly study schedule', points: 15 },
          { day: 3, task: 'Review notes from today\'s classes', points: 10 },
          { day: 4, task: 'Identify your best learning style', points: 15 },
          { day: 5, task: 'Set 3 academic goals for this month', points: 15 },
          { day: 6, task: 'Read for 30 minutes beyond assignments', points: 10 },
          { day: 7, task: 'Plan your assignments for the week', points: 15 },
          { day: 8, task: 'Ask a teacher a question in class', points: 15 },
          { day: 9, task: 'Create flashcards for an upcoming test', points: 15 },
          { day: 10, task: 'Eliminate one study distraction', points: 15 },
        ],
      },
      growth: {
        name: 'Phase 2: Level Up',
        days: [
          { day: 11, task: 'Study with a classmate or form a group', points: 20 },
          { day: 12, task: 'Teach a concept to someone else', points: 25 },
          { day: 13, task: 'Practice active recall for 20 minutes', points: 20 },
          { day: 14, task: 'Review and revise old notes', points: 15 },
          { day: 15, task: 'Complete an assignment one day early', points: 20 },
          { day: 16, task: 'Research a topic you\'re curious about', points: 20 },
          { day: 17, task: 'Use the Pomodoro technique for 2 hours', points: 20 },
          { day: 18, task: 'Seek feedback on your work', points: 20 },
          { day: 19, task: 'Practice past exam questions', points: 25 },
          { day: 20, task: 'Summarize what you learned this week', points: 15 },
        ],
      },
      mastery: {
        name: 'Phase 3: Own Your Future',
        days: [
          { day: 21, task: 'Research colleges or career paths', points: 25 },
          { day: 22, task: 'Create a 5-year academic vision', points: 30 },
          { day: 23, task: 'Connect with a mentor in your field', points: 30 },
          { day: 24, task: 'Enter an academic competition', points: 30 },
          { day: 25, task: 'Present your work to others', points: 25 },
          { day: 26, task: 'Help a struggling classmate', points: 20 },
          { day: 27, task: 'Reflect on your academic growth', points: 15 },
          { day: 28, task: 'Set boundaries around study time', points: 20 },
          { day: 29, task: 'Celebrate your progress', points: 15 },
          { day: 30, task: 'Declare your commitment to excellence', points: 30 },
        ],
      },
    },
  },
  {
    id: 'wellness',
    name: 'Mental Wellness',
    emoji: '🌿',
    color: '#22C55E',
    gradient: 'from-green-600 to-emerald-600',
    subtitle: 'Check In · Build Healthier Patterns · Protect Your Peace',
    description: 'Prioritize your mental health, build sustainable wellness habits, and protect your inner peace.',
    phases: {
      foundation: {
        name: 'Phase 1: Check In',
        days: [
          { day: 1, task: 'Journal: How are you really feeling?', points: 15 },
          { day: 2, task: 'Practice 5 minutes of deep breathing', points: 10 },
          { day: 3, task: 'Identify one stress trigger', points: 15 },
          { day: 4, task: 'Write 3 things you\'re grateful for', points: 10 },
          { day: 5, task: 'Take a 10-minute walk outside', points: 10 },
          { day: 6, task: 'Name your emotions without judgment', points: 15 },
          { day: 7, task: 'Do one thing just for joy today', points: 15 },
          { day: 8, task: 'Practice saying no to one obligation', points: 20 },
          { day: 9, task: 'Create a calming bedtime routine', points: 15 },
          { day: 10, task: 'Limit social media by 30 minutes', points: 15 },
        ],
      },
      growth: {
        name: 'Phase 2: Build Healthier Patterns',
        days: [
          { day: 11, task: 'Replace one negative thought pattern', points: 20 },
          { day: 12, task: 'Practice self-compassion when you mess up', points: 20 },
          { day: 13, task: 'Set a boundary with someone', points: 25 },
          { day: 14, task: 'Try a new wellness activity (yoga, art, etc.)', points: 20 },
          { day: 15, task: 'Write a letter of forgiveness to yourself', points: 25 },
          { day: 16, task: 'Create a worry-free zone/time', points: 20 },
          { day: 17, task: 'Practice mindful eating for one meal', points: 15 },
          { day: 18, task: 'Reach out to someone you trust', points: 20 },
          { day: 19, task: 'Do a digital detox for 2 hours', points: 20 },
          { day: 20, task: 'Create a self-care toolkit', points: 20 },
        ],
      },
      mastery: {
        name: 'Phase 3: Protect Your Peace',
        days: [
          { day: 21, task: 'Design your ideal peaceful day', points: 25 },
          { day: 22, task: 'Teach someone a wellness technique', points: 25 },
          { day: 23, task: 'Release a grudge or resentment', points: 30 },
          { day: 24, task: 'Create morning and evening rituals', points: 20 },
          { day: 25, task: 'Advocate for your mental health needs', points: 30 },
          { day: 26, task: 'Practice radical self-acceptance', points: 25 },
          { day: 27, task: 'Help someone with their mental health', points: 25 },
          { day: 28, task: 'Audit your relationships for peace', points: 25 },
          { day: 29, task: 'Celebrate your emotional growth', points: 15 },
          { day: 30, task: 'Commit to protecting your peace daily', points: 30 },
        ],
      },
    },
  },
  {
    id: 'money',
    name: 'Money Moves',
    emoji: '💰',
    color: '#F59E0B',
    gradient: 'from-amber-500 to-yellow-500',
    subtitle: 'Know Your Money · Build Skills · Build Wealth Mindset',
    description: 'Develop financial literacy, build income-generating skills, and cultivate a wealth-building mindset.',
    phases: {
      foundation: {
        name: 'Phase 1: Know Your Money',
        days: [
          { day: 1, task: 'Track every dollar you spend today', points: 15 },
          { day: 2, task: 'Write down your money beliefs', points: 15 },
          { day: 3, task: 'Research one budgeting method', points: 15 },
          { day: 4, task: 'Calculate your monthly expenses', points: 20 },
          { day: 5, task: 'Set a savings goal', points: 15 },
          { day: 6, task: 'Learn the difference between needs and wants', points: 10 },
          { day: 7, task: 'No-spend day challenge', points: 20 },
          { day: 8, task: 'Research one investment concept', points: 20 },
          { day: 9, task: 'Write down 3 money goals', points: 15 },
          { day: 10, task: 'Review your spending patterns', points: 20 },
        ],
      },
      growth: {
        name: 'Phase 2: Build Skills',
        days: [
          { day: 11, task: 'Learn a skill that could generate income', points: 25 },
          { day: 12, task: 'Research side hustle ideas', points: 20 },
          { day: 13, task: 'Create a simple budget', points: 20 },
          { day: 14, task: 'Save a specific amount today', points: 20 },
          { day: 15, task: 'Read about a successful entrepreneur', points: 15 },
          { day: 16, task: 'Practice negotiating something', points: 25 },
          { day: 17, task: 'Identify your marketable skills', points: 20 },
          { day: 18, task: 'Create a resume or portfolio', points: 25 },
          { day: 19, task: 'Research passive income ideas', points: 25 },
          { day: 20, task: 'Automate one savings habit', points: 25 },
        ],
      },
      mastery: {
        name: 'Phase 3: Build Wealth Mindset',
        days: [
          { day: 21, task: 'Create a 5-year financial vision', points: 30 },
          { day: 22, task: 'Start a money-making project', points: 30 },
          { day: 23, task: 'Invest in your education/skills', points: 25 },
          { day: 24, task: 'Network with someone financially successful', points: 30 },
          { day: 25, task: 'Teach someone about money', points: 20 },
          { day: 26, task: 'Review and adjust your budget', points: 20 },
          { day: 27, task: 'Give generously (time or money)', points: 20 },
          { day: 28, task: 'Affirm your wealth-building identity', points: 20 },
          { day: 29, task: 'Celebrate your financial wins', points: 15 },
          { day: 30, task: 'Commit to lifelong financial growth', points: 30 },
        ],
      },
    },
  },
  {
    id: 'leadership',
    name: 'Leadership & Impact',
    emoji: '✨',
    color: '#EC4899',
    gradient: 'from-pink-500 to-rose-500',
    subtitle: 'Discover · Lead Where You Are · Create Real Impact',
    description: 'Discover your leadership style, take initiative in your community, and create lasting positive impact.',
    phases: {
      foundation: {
        name: 'Phase 1: Discover',
        days: [
          { day: 1, task: 'Write about a leader you admire', points: 15 },
          { day: 2, task: 'Identify your leadership strengths', points: 15 },
          { day: 3, task: 'Reflect on a time you led well', points: 20 },
          { day: 4, task: 'Identify a problem you want to solve', points: 20 },
          { day: 5, task: 'Write your leadership vision', points: 20 },
          { day: 6, task: 'Practice active listening today', points: 15 },
          { day: 7, task: 'Take initiative on one task', points: 20 },
          { day: 8, task: 'Research a cause you care about', points: 20 },
          { day: 9, task: 'Identify your sphere of influence', points: 15 },
          { day: 10, task: 'Practice empathy with someone', points: 15 },
        ],
      },
      growth: {
        name: 'Phase 2: Lead Where You Are',
        days: [
          { day: 11, task: 'Volunteer for a leadership role', points: 25 },
          { day: 12, task: 'Organize a small event or gathering', points: 30 },
          { day: 13, task: 'Mentor someone younger', points: 25 },
          { day: 14, task: 'Speak up for someone else', points: 25 },
          { day: 15, task: 'Start a project or initiative', points: 30 },
          { day: 16, task: 'Delegate a task effectively', points: 20 },
          { day: 17, task: 'Give constructive feedback kindly', points: 20 },
          { day: 18, task: 'Collaborate on a team project', points: 20 },
          { day: 19, task: 'Solve a problem in your community', points: 30 },
          { day: 20, task: 'Inspire someone through your actions', points: 25 },
        ],
      },
      mastery: {
        name: 'Phase 3: Create Real Impact',
        days: [
          { day: 21, task: 'Launch a community project', points: 35 },
          { day: 22, task: 'Speak publicly about a cause', points: 30 },
          { day: 23, task: 'Build a team around your vision', points: 35 },
          { day: 24, task: 'Create something that outlasts you', points: 35 },
          { day: 25, task: 'Partner with an organization', points: 30 },
          { day: 26, task: 'Document your leadership journey', points: 20 },
          { day: 27, task: 'Empower someone to lead', points: 30 },
          { day: 28, task: 'Measure your impact', points: 25 },
          { day: 29, task: 'Celebrate lives you\'ve touched', points: 20 },
          { day: 30, task: 'Commit to lifelong leadership growth', points: 35 },
        ],
      },
    },
  },
];

export const PHASE_INFO = {
  foundation: { name: 'Foundation', emoji: '🌱', description: 'Build your base' },
  growth: { name: 'Growth', emoji: '🌿', description: 'Level up' },
  mastery: { name: 'Mastery', emoji: '👑', description: 'Master it' },
};

export const getChallengeById = (id) => CHALLENGES.find(c => c.id === id);

export const getAllDays = (challenge) => {
  const allDays = [];
  Object.values(challenge.phases).forEach(phase => {
    allDays.push(...phase.days);
  });
  return allDays;
};

export const getTotalPoints = (challenge) => {
  return getAllDays(challenge).reduce((sum, day) => sum + day.points, 0);
};